ALTER TYPE "PublicProjectSourceKey" ADD VALUE IF NOT EXISTS 'NIH_REPORTER';
ALTER TYPE "PublicProjectSourceKey" ADD VALUE IF NOT EXISTS 'NSF';
ALTER TYPE "PublicProjectSourceKey" ADD VALUE IF NOT EXISTS 'CORDIS';
ALTER TYPE "PublicProjectSourceKey" ADD VALUE IF NOT EXISTS 'UKRI_GTR';
ALTER TYPE "PublicProjectSourceKey" ADD VALUE IF NOT EXISTS 'NWO';
