import type {
  GrantPrepDiscussionPointDefinition,
  GrantPrepStageDefinition,
  GrantPrepStageKey,
} from './types';

function points(items: Array<[string, string, 'P1' | 'P2' | 'P3', string, string[]]>): GrantPrepDiscussionPointDefinition[] {
  return items.map(([key, label, priority, helpText, templateKeywords]) => ({
    key,
    label,
    priority,
    helpText,
    templateKeywords,
  }));
}

export const GRANT_PREP_STAGE_LIBRARY: GrantPrepStageDefinition[] = [
  {
    key: 'problem_definition',
    title: 'Problem Definition',
    category: 'framing',
    description: 'Clarify the problem, scale, urgency, and why it matters now.',
    askStyle: 'Keep it concrete and evidence-led.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['priorities', 'mustAddress', 'evaluationCriteria'],
    steeringRule: 'Do not accept a vague problem statement without a target population or urgency signal. Do not accept a textbook framing of a well-known issue without a sharper angle, gap, or timely reason this proposal stands out now.',
    dependencies: [],
    defaultPoints: points([
      ['problem_core', 'Core problem statement', 'P1', 'One sentence on the real problem being solved.', ['problem', 'challenge', 'need']],
      ['problem_scale', 'Scale and urgency', 'P1', 'Magnitude, timing, or why action is timely.', ['urgent', 'burden', 'gap']],
      ['evidence_gap', 'Evidence or practice gap', 'P2', 'What is currently missing or insufficient.', ['gap', 'baseline', 'evidence']],
    ]),
    reviewerRubric: {
      strong: 'Specific problem with quantified scale, a clear urgency driver or time pressure, an identified evidence or practice gap, a target population defined with operational criteria, and a framing that does not read like a standard textbook version of the topic.',
      adequate: 'Problem stated with some scale but urgency is implied not proven, target population named but not operationally defined, and the framing could still describe many similar proposals.',
      weak: 'Generic or textbook problem statement with no quantification, no urgency signal, no gap identification, or no angle that would distinguish the proposal from common submissions on the topic.',
    },
  },
  {
    key: 'root_cause',
    title: 'Root Cause',
    category: 'framing',
    description: 'Move past symptoms and identify the drivers behind the problem.',
    askStyle: 'Push at least one level deeper than surface explanations.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['mustAddress', 'reviewerSignals'],
    steeringRule: 'Avoid restating the problem as its own cause. Push for the specific mechanism, system failure, or institutional constraint that reviewers can connect to the intervention logic.',
    dependencies: ['problem_definition'],
    defaultPoints: points([
      ['root_drivers', 'Underlying drivers', 'P1', 'Primary structural or operational causes.', ['driver', 'cause', 'constraint']],
      ['current_failure', 'Why current approaches fall short', 'P2', 'Explain why the status quo is not enough.', ['current', 'failure', 'limitation']],
    ]),
    reviewerRubric: {
      strong: 'Identifies structural or systemic drivers distinct from the problem itself, explains why existing approaches fail, and connects those mechanisms to the proposed intervention logic.',
      adequate: 'Names one or two causes but does not clearly distinguish them from symptoms, with limited analysis of current approach failures.',
      weak: 'Restates the problem as its own cause, names only surface symptoms, or offers no analysis of why current approaches fail.',
    },
  },
  {
    key: 'beneficiaries',
    title: 'Beneficiaries',
    category: 'framing',
    description: 'Specify who benefits, how, and where.',
    askStyle: 'Identify direct and indirect beneficiaries precisely.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['priorities', 'mustAddress'],
    steeringRule: 'Do not allow a beneficiary group with no operational definition, no access path, or no context explaining why this population matters for this call.',
    dependencies: ['problem_definition'],
    defaultPoints: points([
      ['direct_beneficiaries', 'Direct beneficiaries', 'P1', 'Who directly receives value from the project.', ['beneficiary', 'target group', 'end user']],
      ['indirect_beneficiaries', 'Indirect beneficiaries', 'P2', 'Who benefits secondarily or systemically.', ['stakeholder', 'community', 'system']],
      ['geography_context', 'Geographic or institutional context', 'P2', 'Where the work happens or who hosts it.', ['site', 'region', 'institution']],
    ]),
    reviewerRubric: {
      strong: 'Direct beneficiaries are operationally defined with a size estimate or inclusion criteria, indirect beneficiaries are identified, and the geographic or institutional context makes clear why this population is the right focus.',
      adequate: 'Beneficiaries are named but not operationally defined, no size estimate is given, and the geographic or institutional context is still vague.',
      weak: 'Uses generic groups like "the community" or "students" with no operational definition, no access path, or no explanation of why this population is the right focus for the call.',
    },
  },
  {
    key: 'fit_and_scope',
    title: 'Fit and Scope',
    category: 'alignment',
    description: 'Confirm the proposal fits the call, its scale, and the applicant profile.',
    askStyle: 'Frame the work at the right scope for the funding call.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['priorities', 'mustAddress', 'avoid'],
    steeringRule: 'Flag out-of-scope ambitions or unqualified applicant framing.',
    dependencies: ['problem_definition', 'beneficiaries'],
    defaultPoints: points([
      ['call_fit', 'Why this call fits the project', 'P1', 'Explain fit to the scheme and agency.', ['fit', 'scheme', 'alignment']],
      ['scope_control', 'Right-sized scope', 'P1', 'Keep scope realistic for funding, time, and team.', ['scope', 'feasible', 'phased']],
    ]),
    reviewerRubric: {
      strong: 'Clear mapping between project objectives and call priorities, scope is realistic for budget and timeline, applicant profile is justified.',
      adequate: 'Fit claimed but not mapped to specific call criteria, scope seems reasonable but not explicitly justified.',
      weak: 'No connection drawn between project and call, scope is either too ambitious or too narrow without explanation.',
    },
  },
  {
    key: 'thrust_alignment',
    title: 'Priority Alignment',
    category: 'alignment',
    description: 'Link the proposal to call priorities or thrust areas.',
    askStyle: 'Use the call language precisely, without keyword stuffing.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['priorities', 'evaluationCriteria', 'reviewerSignals'],
    steeringRule: 'Every priority claim must connect to the proposed work, not just repeat call words.',
    dependencies: ['fit_and_scope'],
    defaultPoints: points([
      ['priority_match', 'Priority or thrust alignment', 'P1', 'Name the relevant priorities and why they fit.', ['priority', 'theme', 'thrust']],
      ['reviewer_signal', 'Reviewer value signal', 'P2', 'What reviewers are likely to reward here.', ['impact', 'fit', 'merit']],
    ]),
    reviewerRubric: {
      strong: 'Specific call priorities named and connected to concrete project activities, reviewer value signal articulates merit beyond fit.',
      adequate: 'Priorities mentioned but connection to project is generic, reviewer signal is vague.',
      weak: 'Call keywords repeated without connecting to the proposed work.',
    },
  },
  {
    key: 'methodology',
    title: 'Methodology',
    category: 'design',
    description: 'Describe the core approach, methods, and implementation logic.',
    askStyle: 'Keep it implementable and specific.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['mustAddress', 'evaluationCriteria', 'durationRules'],
    steeringRule: 'Methodology must describe how the work is done, not just its goals.',
    dependencies: ['problem_definition', 'root_cause'],
    defaultPoints: points([
      ['approach', 'Core approach', 'P1', 'High-level method or intervention design.', ['approach', 'method', 'intervention']],
      ['activities', 'Key activities or work packages', 'P1', 'Main actions the team will take.', ['activity', 'work package', 'task']],
      ['evidence_generation', 'Data, validation, or evidence plan', 'P2', 'How the project generates proof or validation.', ['data', 'evaluation', 'pilot']],
    ]),
    reviewerRubric: {
      strong: 'Clear intervention logic connecting problem to approach, named methods with justification, defined data collection or validation strategy, and feasibility evidence.',
      adequate: 'Approach described but methods are generic, validation plan is vague, feasibility assumed without evidence.',
      weak: 'Approach is a goal restatement, no described methods, no validation or evidence plan.',
    },
  },
  {
    key: 'workplan',
    title: 'Workplan',
    category: 'design',
    description: 'Lay out phases, milestones, and delivery rhythm.',
    askStyle: 'Sequence the work from start to finish.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['durationRules', 'deliverableRules'],
    steeringRule: 'Milestones must fit the call duration and deliverable expectations.',
    dependencies: ['methodology'],
    defaultPoints: points([
      ['phases', 'Project phases', 'P1', 'Major phases or milestones.', ['phase', 'milestone', 'timeline']],
      ['deliverables', 'Expected outputs', 'P1', 'Concrete deliverables by phase or end state.', ['deliverable', 'output', 'report']],
    ]),
    reviewerRubric: {
      strong: 'Phases are sequenced logically with clear milestones, deliverables are concrete and time-bound, schedule fits the call duration.',
      adequate: 'Phases listed but milestones are vague, deliverables named but not tied to specific phases.',
      weak: 'No phasing, milestones are aspirational, deliverables not specified.',
    },
  },
  {
    key: 'team_and_partnerships',
    title: 'Team and Partnerships',
    category: 'design',
    description: 'Explain who will do the work and what collaborators add.',
    askStyle: 'Highlight execution capacity, not resumes.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['mustAddress', 'evaluationCriteria'],
    steeringRule: 'Do not allow unnamed capability claims with no operational role.',
    dependencies: ['methodology'],
    defaultPoints: points([
      ['team_roles', 'Execution roles', 'P1', 'Who leads, delivers, and validates the work.', ['team', 'role', 'expertise']],
      ['partners', 'Partners or stakeholders', 'P2', 'External collaborators and why they matter.', ['partner', 'stakeholder', 'collaboration']],
    ]),
    reviewerRubric: {
      strong: 'Named roles with clear responsibilities, relevant expertise justified, partnerships have defined contributions and commitment evidence.',
      adequate: 'Roles described generically, expertise claimed but not tied to project tasks, partnerships mentioned without defined roles.',
      weak: 'No named roles, capability claims without operational detail, no partnership information.',
    },
  },
  {
    key: 'innovation',
    title: 'Innovation',
    category: 'alignment',
    description: 'Describe what is novel or meaningfully better about the proposal.',
    askStyle: 'Novelty must be comparative, not generic.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['evaluationCriteria', 'reviewerSignals'],
    steeringRule: 'Innovation claims must say compared to what and why a reviewer would notice the difference.',
    dependencies: ['methodology'],
    defaultPoints: points([
      ['novelty_claim', 'What is different', 'P1', 'The novelty or meaningful advantage.', ['innovation', 'novel', 'advance']],
      ['comparative_value', 'Compared with current practice', 'P2', 'Why this is better than existing options.', ['compare', 'advantage', 'improvement']],
    ]),
    reviewerRubric: {
      strong: 'Innovation claim is specific, comparative against named current practice, and connected to a meaningful reviewer-visible advantage in outcomes, feasibility, or relevance.',
      adequate: 'Claims novelty but comparison is generic, against an unstated baseline, or not clearly tied to why the difference matters.',
      weak: 'Uses words like "innovative" or "novel" without any comparison, specificity, or reviewer-visible advantage.',
    },
  },
  {
    key: 'evaluation',
    title: 'Evaluation',
    category: 'delivery',
    description: 'Define how success is assessed and evidenced.',
    askStyle: 'Tie measures to outcomes and verification methods.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['evaluationCriteria', 'mustAddress'],
    steeringRule: 'Success measures must be observable or measurable.',
    dependencies: ['methodology', 'outcomes'],
    defaultPoints: points([
      ['success_metrics', 'Success metrics', 'P1', 'Measures that show the project worked.', ['metric', 'indicator', 'measure']],
      ['verification', 'Verification approach', 'P2', 'How outcomes will be verified or monitored.', ['monitoring', 'evaluation', 'verification']],
    ]),
    reviewerRubric: {
      strong: 'Metrics are specific, measurable, tied to stated outcomes, with a named verification method and timeline.',
      adequate: 'Metrics listed but not clearly tied to outcomes, verification approach is vague.',
      weak: 'No defined metrics, success is described aspirationally without measurement.',
    },
  },
  {
    key: 'outcomes',
    title: 'Outcomes',
    category: 'delivery',
    description: 'State the near-term and longer-term outcomes.',
    askStyle: 'Keep outputs distinct from outcomes.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['mustAddress', 'evaluationCriteria', 'reviewerSignals'],
    steeringRule: 'Do not confuse activities with outcomes.',
    dependencies: ['methodology'],
    defaultPoints: points([
      ['near_term_outcomes', 'Near-term outcomes', 'P1', 'Immediate changes expected during the project.', ['outcome', 'short-term', 'benefit']],
      ['long_term_outcomes', 'Longer-term effect', 'P2', 'What this enables after project completion.', ['impact', 'scale', 'adoption']],
    ]),
    reviewerRubric: {
      strong: 'Outcomes are distinct from activities, near-term changes are specific and observable, longer-term effects have a plausible pathway.',
      adequate: 'Outcomes stated but conflated with activities, longer-term effects are aspirational without a pathway.',
      weak: 'Activities listed as outcomes, no distinction between short-term and long-term effects.',
    },
  },
  {
    key: 'risk_and_ethics',
    title: 'Risk and Ethics',
    category: 'delivery',
    description: 'Capture major risks, ethics, and mitigation.',
    askStyle: 'Name realistic risks and how they are handled.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['avoid', 'mustAddress', 'reviewerSignals'],
    steeringRule: 'Risk handling must be concrete, not a generic assurance statement.',
    dependencies: ['methodology'],
    defaultPoints: points([
      ['execution_risks', 'Execution risks', 'P1', 'Delivery, recruitment, data, or dependency risks.', ['risk', 'constraint', 'dependency']],
      ['mitigation', 'Mitigation strategy', 'P1', 'What the team will do if risks materialize.', ['mitigation', 'fallback', 'contingency']],
      ['ethics', 'Ethics or compliance considerations', 'P2', 'Any ethics, regulatory, or safety considerations.', ['ethics', 'compliance', 'approval']],
    ]),
    reviewerRubric: {
      strong: 'Realistic risks named with likelihood assessment, concrete mitigation actions for each, ethics considerations addressed with compliance pathway.',
      adequate: 'Risks listed but generic, mitigation is "we will monitor," ethics mentioned without a compliance plan.',
      weak: 'No specific risks identified, mitigation is a generic assurance, ethics not addressed.',
    },
  },
  {
    key: 'budget_strategy',
    title: 'Budget Strategy',
    category: 'delivery',
    description: 'Outline the spending logic and what the funds cover.',
    askStyle: 'Keep it high level but call-compliant.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['budgetRules', 'durationRules', 'avoid'],
    steeringRule: 'Budget logic must match the call size and rules.',
    dependencies: ['workplan'],
    defaultPoints: points([
      ['budget_logic', 'Budget logic', 'P1', 'How major cost categories connect to work.', ['budget', 'cost', 'resource']],
      ['budget_constraints', 'Call-specific budget constraints', 'P2', 'Caps, exclusions, or justification expectations.', ['cap', 'allowable', 'non-allowable']],
    ]),
    reviewerRubric: {
      strong: 'Cost categories linked to specific activities, proportions justified, call-specific constraints addressed, value for money argued.',
      adequate: 'Budget categories listed but links to activities are loose, constraints acknowledged but not fully addressed.',
      weak: 'Lump-sum budget with no activity linkage, call constraints not addressed.',
    },
  },
  {
    key: 'sustainability_and_scale',
    title: 'Sustainability and Scale',
    category: 'delivery',
    description: 'Explain continuation, adoption, or scaling if relevant.',
    askStyle: 'Treat sustainability as operational, not aspirational.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['reviewerSignals', 'mustAddress'],
    steeringRule: 'Do not promise scale without a plausible path.',
    dependencies: ['outcomes'],
    defaultPoints: points([
      ['continuity', 'Continuation after funding', 'P2', 'How value persists after the grant ends.', ['sustainability', 'continuation', 'maintenance']],
      ['scale_path', 'Adoption or scale path', 'P3', 'Who could adopt or expand the work.', ['scale', 'adoption', 'replication']],
    ]),
    reviewerRubric: {
      strong: 'Concrete continuation plan with named funding or operational path, adoption pathway identifies specific adopters and conditions.',
      adequate: 'Sustainability mentioned with general intent, adoption path is aspirational without named adopters.',
      weak: 'No continuation plan, scale claims without any pathway.',
    },
  },
  {
    key: 'final_pitch',
    title: 'Final Pitch',
    category: 'delivery',
    description: 'Condense the strongest version of the proposal.',
    askStyle: 'Focus on sharp positioning for the handoff payload.',
    defaultEnabled: true,
    pickable: true,
    guidelineBlocks: ['priorities', 'reviewerSignals'],
    steeringRule: 'The summary must reflect captured facts, not new claims.',
    dependencies: ['outcomes', 'risk_and_ethics'],
    defaultPoints: points([
      ['one_line_pitch', 'One-line pitch', 'P1', 'The shortest credible description of the project.', ['summary', 'pitch', 'positioning']],
      ['reviewer_case', 'Why reviewers should fund this', 'P1', 'The strongest combined case for support.', ['why now', 'fit', 'value']],
    ]),
    reviewerRubric: {
      strong: 'One-line pitch is crisp, credible, and captures the unique value. Reviewer case synthesizes captured facts into a compelling argument.',
      adequate: 'Pitch exists but is generic, reviewer case restates facts without synthesis.',
      weak: 'No clear pitch, reviewer case introduces new claims not captured in prior stages.',
    },
  },
  {
    key: 'handoff_ready',
    title: 'Handoff Ready',
    category: 'terminal',
    description: 'Readiness checkpoint before sending to Papsi.',
    askStyle: 'No new content should be introduced here.',
    defaultEnabled: true,
    pickable: false,
    guidelineBlocks: [],
    steeringRule: 'This stage exists only as a checkpoint.',
    dependencies: ['final_pitch'],
    defaultPoints: [],
  },
  {
    key: 'handoff_complete',
    title: 'Handoff Complete',
    category: 'terminal',
    description: 'External writing has been launched.',
    askStyle: 'Terminal state.',
    defaultEnabled: true,
    pickable: false,
    guidelineBlocks: [],
    steeringRule: 'This stage is terminal.',
    dependencies: ['handoff_ready'],
    defaultPoints: [],
  },
];

export const GRANT_PREP_STAGE_BY_KEY: Record<GrantPrepStageKey, GrantPrepStageDefinition> =
  GRANT_PREP_STAGE_LIBRARY.reduce((acc, stage) => {
    acc[stage.key] = stage;
    return acc;
  }, {} as Record<GrantPrepStageKey, GrantPrepStageDefinition>);

export function getPickableGrantPrepStageKeys(): GrantPrepStageKey[] {
  return GRANT_PREP_STAGE_LIBRARY.filter((stage) => stage.pickable).map((stage) => stage.key);
}

export function getDefaultEnabledStageKeys(): GrantPrepStageKey[] {
  return GRANT_PREP_STAGE_LIBRARY.filter((stage) => stage.defaultEnabled).map((stage) => stage.key);
}
