'use client'

import Link from 'next/link'
import { Fragment, useCallback, useEffect, useId, useRef, useState } from 'react'
import { useAuth } from '@/lib/auth-context'
import { useFundingDeptMe } from '@/lib/client/useFundingDeptMe'
import AssignDialog from '@/components/funding-dept/AssignDialog'
import FollowUpPanel from '@/components/funding-dept/FollowUpPanel'
import type { ManagementReport } from '@/lib/fundingDept/managementService'

type Wire<T> = T extends Date ? string : T extends Array<infer U> ? Wire<U>[] : T extends object ? { [K in keyof T]: Wire<T[K]> } : T
type Report = Wire<ManagementReport>
type App = Report['applications'][number]
type Call = Report['members'][number]['schools'][number]['calls'][number]
type Action = Report['actions'][number]
type Person = { id:string; name:string | null }
type Payload = { snapshot?:string; members?:Report['members']; rows?:any[]; total?:number; totals:Report['totals']; attentionCounts:{upcoming21:number;missedUnallocatedNoSubmission:number}; quality:Report['quality']; options:Report['options']; activity:Report['activity']; asOf:string; windowLabel:string; lens:string; portfolio:string; membersMovement?:any[]; complete?:boolean; note?:string; definition?:string; urgentActions?:Action[]; urgentOpportunities?:any[]; unallocated?:Call[]; actions?:Action[]; headSummary?:any }
const views = [['workbench','My school desk'],['member-funnel','Member → school → call'],['school-coverage','School call coverage'],['opportunity-gaps','Opportunity action gaps'],['pending','Pending work'],['deadline-risk','Deadline risk'],['coverage','Faculty coverage'],['outcomes','Submissions & outcomes'],['performance','Member performance'],['weekly-review','Weekly review']]
const label = (s:string) => s.toLowerCase().replace(/_/g,' ').replace(/^./,c=>c.toUpperCase())
const date = (s?:string|null) => s ? new Date(s).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric'}) : 'Not recorded'
const field = 'rounded border border-nickel-300 bg-white px-2 py-1.5 text-sm'
const stages = ['AWAITING_FACULTY_RESPONSE','ACCEPTED_IN_HAND','PROPOSAL_DRAFTING','INTERNAL_REVIEW','CLEARED_AND_READY','SUBMITTED','UNDER_AGENCY_REVIEW','REVISION_REQUESTED','SANCTIONED','REJECTED','DECLINED','CANCELLED','LAPSED_NOT_APPLIED']

function HelpButton({help,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{help:string}) {
  const id=useId()
  return <span className="group relative inline-flex"><button {...props} title={help} aria-describedby={id}>{children}</button><span id={id} role="tooltip" className="pointer-events-none absolute left-1/2 top-full z-50 mt-2 hidden w-64 -translate-x-1/2 rounded border border-nickel-200 bg-white p-2 text-left text-xs font-normal text-nickel-700 shadow-lg group-hover:block group-focus-within:block">{help}</span></span>
}
const deadlineCopy=(c:Call)=>c.daysToDeadline===null?'Deadline not recorded':c.daysToDeadline<0?`${Math.abs(c.daysToDeadline)} day${Math.abs(c.daysToDeadline)===1?'':'s'} missed`:c.daysToDeadline===0?'Due today':`${c.daysToDeadline} day${c.daysToDeadline===1?'':'s'} remaining`

function useReport(path:string, revision=0) {
  const { authFetch }=useAuth();const [data,setData]=useState<Payload|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [loadedPath,setLoadedPath]=useState('')
  useEffect(()=>{let current=true;setLoading(true);setError('');authFetch(path).then(async r=>{const json=await r.json();if(!r.ok)throw Error(json.error||'Unable to load report');if(current){setData(json);setLoadedPath(path)}}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[path,revision,authFetch])
  return {data,error,loading,loadedPath}
}
function Pager({page,total=0,onChange}:{page:number;total?:number;onChange:(n:number)=>void}) {return <div className="flex items-center justify-end gap-3 p-3 text-sm"><span>{total} records · Page {page} of {Math.max(1,Math.ceil(total/20))}</span><HelpButton help={page<=1?'You are already on the first page.':'Show the previous 20 filtered records.'} className="nk-btn-secondary nk-btn-xs" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</HelpButton><HelpButton help={page*20>=total?'You are already on the last page.':'Show the next 20 filtered records.'} className="nk-btn-secondary nk-btn-xs" disabled={page*20>=total} onClick={()=>onChange(page+1)}>Next</HelpButton></div>}
function Table({head,children}:{head:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-nickel-50"><tr>{head.map(h=><th key={h} className="px-3 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Cell({children}:{children:React.ReactNode}){return <td className="border-t border-nickel-100 px-3 py-3 align-top">{children}</td>}
function Ratio({value}:{value:{numerator:number;denominator:number;percent:number|null}}){return <span>{value.numerator}/{value.denominator} ({value.percent===null?'—':`${Math.round(value.percent)}%`})</span>}
function AppTable({apps,onOpen}:{apps:App[];onOpen:(id:string)=>void}) {return <Table head={['Faculty / application','Accountable / next owner','Stage / work state','Days waiting','Follow-up','Deadlines','Submission']}>
  {apps.map(a=><tr key={a.id}><Cell><button title="Open the application details, follow-up log, evidence and next actions." className="text-cobalt-700 text-left font-medium hover:underline" onClick={()=>onOpen(a.id)}>{a.faculty?.name || 'Faculty not recorded'}</button><p className="nk-sub">{a.title}</p><span className="nk-badge">{a.independent?'Independent application':'Formal allocation'}</span></Cell>
    <Cell>{(a as App & {accountableOfficer?:string}).accountableOfficer || 'See portfolio'}<p>{a.nextAction?.owner_name || 'Next owner not confirmed'}</p><p className="nk-sub">{a.nextAction?.title || 'Confirm a next action'}</p>{a.nextAction?.waiting_with==='AGENCY'&&<p className="nk-sub">Waiting externally; DSR follow-up owner above</p>}</Cell>
    <Cell>{label(a.stage)}<p className="nk-sub">{label(a.workState)}</p>{a.exceptions.map(e=><span className="nk-badge nk-badge-warn mr-1" key={e}>{label(e.replace(/-/g,'_'))}</span>)}</Cell>
    <Cell>{a.daysWaiting===null?'Not recorded':`${a.daysWaiting} days`}<p className="nk-sub">Since {date(a.stageEnteredAt)}</p></Cell>
    <Cell>{a.contactEvents} faculty contacts<p className="nk-sub">{a.lastContact?`Performed by ${a.lastContact.actor_name}`:'No external faculty contact'}</p></Cell>
    <Cell><p>Agency: {date(a.agency_deadline)}</p><p>Internal: {date(a.internal_deadline)}</p><p>Review: {date(a.review_deadline)}</p><p>Action: {date(a.nextAction?.due_at)}</p></Cell>
    <Cell>{a.submitted?(a.verification?'Verified':'Recorded · unverified'):'Not submitted'}<p className="nk-sub">{a.submitted?date(a.submitted_at):''}</p></Cell></tr>)}
    {!apps.length&&<tr><td colSpan={7} className="p-6 text-center nk-sub">No applications match these filters.</td></tr>}
  </Table>}

export default function ManagementWorkspace({initialWindow='reporting'}:{initialWindow?:string}) {
  const {authFetch}=useAuth();const [view,setView]=useState('workbench');const [filters,setFilters]=useState<Record<string,string>>({window:initialWindow,mode:'pending'});const [page,setPage]=useState(1);const [expanded,setExpanded]=useState<Record<string,boolean>>({});const [detail,setDetail]=useState<string|null>(null);const [personDetail,setPersonDetail]=useState<{id:string;name:string}|null>(null);const [revision,setRevision]=useState(0);const [exportError,setExportError]=useState('')
  const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const base=query.toString();query.set('page',String(page))
  const snapshotCache=useRef(new Map<string,string>());const identity=`${view}?${base}@${revision}`;const cached=snapshotCache.current.get(identity);if(cached)query.set('snapshot',cached)
  const reportUrl=`/api/funding-dept/reports/${view}?${query}`
  const {data,error,loading,loadedPath}=useReport(reportUrl,revision)
  if(data?.snapshot && loadedPath===reportUrl)snapshotCache.current.set(identity,data.snapshot)
  const detailQuery=`${base}&snapshot=${data?.snapshot||''}`
  const catalog=useRef<Payload['options']|null>(null)
  if(data && (!catalog.current || (!filters.memberId&&!filters.schoolId&&!filters.callId)))catalog.current=data.options
  const update=(key:string,value:string)=>{setFilters(f=>({...f,[key]:value}));setPage(1)}
  const applyQuick=(kind:'upcoming-21'|'missed-unallocated-no-submission'|'matched-unallocated'|'no-next-action')=>{setFilters(f=>{
    const attention=kind==='upcoming-21'||kind==='missed-unallocated-no-submission'?kind:''
    const exception=kind==='matched-unallocated'||kind==='no-next-action'?kind:''
    const active=(attention&&f.attention===attention)||(exception&&f.exception===exception)
    return {...f,mode:'pending',attention:active?'':attention,exception:active?'':exception,horizon:''}
  });setPage(1)}
  const toggle=(id:string)=>setExpanded(e=>({...e,[id]:!e[id]}))
  const refresh=()=>setRevision(r=>r+1)
  const closeDetail=useCallback(()=>setDetail(null),[])
  const select=(key:string,title:string,options:Array<[string,string]>)=><label className="flex flex-col gap-1 text-xs">{title}<select className={field} value={filters[key]||''} onChange={e=>update(key,e.target.value)}><option value="">All</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
  const exportReport=async(format:string)=>{setExportError('');try{const response=await authFetch(`/api/funding-dept/reports/${view}?${detailQuery}&format=${format}`);if(!response.ok)throw Error((await response.json()).error);const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`dsr-${view}.${format}`;a.click();URL.revokeObjectURL(url)}catch(e){setExportError((e as Error).message)}}
  return <div className="space-y-5">
    <nav className="flex flex-wrap gap-2 border-b border-nickel-200 pb-3" aria-label="Management reports">{views.map(([id,name])=><HelpButton key={id} help={`Open the ${name} report using the current portfolio filters.`} className={view===id?'nk-btn-primary nk-btn-sm':'nk-btn-secondary nk-btn-sm'} onClick={()=>{setView(id);if(id==='school-coverage')setFilters(f=>({...f,mode:'portfolio'}));else if(['pending','deadline-risk','opportunity-gaps','coverage'].includes(id))setFilters(f=>({...f,mode:'pending'}));setPage(1)}}>{name}</HelpButton>)}</nav>
    <div className="nk-panel p-4 space-y-3"><div className="flex flex-wrap items-end gap-3">
      <label className="flex flex-col gap-1 text-xs">Report view<select className={field} value={filters.mode} disabled={view==='school-coverage'} onChange={e=>update('mode',e.target.value)}><option value="pending">Pending now · all ages</option><option value="portfolio">All mapped opportunities</option><option value="cohort">Opportunity cohort</option><option value="activity">Period activity</option></select></label>
      <label className="flex flex-col gap-1 text-xs">Period<select className={field} value={filters.window} onChange={e=>update('window',e.target.value)}><option value="reporting">Department reporting period</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="custom">Custom dates</option></select></label>
      {filters.window==='custom'&&<><label className="text-xs">From <input aria-label="From date" type="date" className={field} value={filters.from||''} onChange={e=>update('from',e.target.value)}/></label><label className="text-xs">To <input aria-label="To date" type="date" className={field} value={filters.to||''} onChange={e=>update('to',e.target.value)}/></label></>}
      {data?.lens==='department'&&select('memberId','Primary member',(catalog.current?.members||[]).map(m=>[m.id,m.name]))}
      {select('schoolId','School',(catalog.current?.schools||[]).map(s=>[s.id,s.name]))}
      <label className="flex flex-col gap-1 text-xs">Call filter<input placeholder="Call title or identifier" className={field} value={filters.callSearch||''} onChange={e=>update('callSearch',e.target.value)}/></label>
      <label className="flex items-center gap-2 pb-2 text-xs"><input type="checkbox" checked={filters.includeExpired==='true'} onChange={e=>update('includeExpired',e.target.checked?'true':'')}/> Include expired calls</label>
      {data?.lens==='member'&&<label className="flex flex-col gap-1 text-xs">Portfolio<select className={field} value={filters.portfolio||'primary'} onChange={e=>{update('portfolio',e.target.value);catalog.current=null}}><option value="primary">My primary accountability</option><option value="deputy">My deputy operational view</option></select></label>}
    </div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
      <HelpButton help="Show confirmed relevant calls due today through the next 21 India calendar days that still have open work or no allocation." className={`${filters.attention==='upcoming-21'?'border-cobalt-500 bg-cobalt-50':'border-nickel-200 bg-white'} rounded border p-3 text-left`} onClick={()=>applyQuick('upcoming-21')}><span className="block text-xs text-nickel-600">Due in next 3 weeks</span><span className="block text-xl font-semibold">{data?.attentionCounts?.upcoming21??'—'}</span></HelpButton>
      <HelpButton help="Show confirmed relevant calls whose deadline passed with no formal allocation and no recorded submission." className={`${filters.attention==='missed-unallocated-no-submission'?'border-red-400 bg-red-50':'border-nickel-200 bg-white'} rounded border p-3 text-left`} onClick={()=>applyQuick('missed-unallocated-no-submission')}><span className="block text-xs text-nickel-600">Missed: no allocation or submission</span><span className="block text-xl font-semibold">{data?.attentionCounts?.missedUnallocatedNoSubmission??'—'}</span></HelpButton>
      <HelpButton help="Show relevant calls with saved researcher matches but nobody formally allocated." className={`${filters.exception==='matched-unallocated'?'border-amber-400 bg-amber-50':'border-nickel-200 bg-white'} rounded border p-3 text-left`} onClick={()=>applyQuick('matched-unallocated')}><span className="block text-xs text-nickel-600">Matched, not allocated</span><span className="block text-xl font-semibold">{data?.totals?.matchedUnallocated??'—'}</span></HelpButton>
      <HelpButton help="Show pending applications that do not have a confirmed next action and named owner." className={`${filters.exception==='no-next-action'?'border-amber-400 bg-amber-50':'border-nickel-200 bg-white'} rounded border p-3 text-left`} onClick={()=>applyQuick('no-next-action')}><span className="block text-xs text-nickel-600">Pending without next action</span><span className="block text-xl font-semibold">{data?.totals?.noNextAction??'—'}</span></HelpButton>
    </div><details><summary className="cursor-pointer text-sm">Status, quality and exception filters</summary><div className="flex flex-wrap gap-3 pt-3">
      {select('workState','Work state',[['PENDING','Pending'],['SUBMITTED','Submitted'],['CLOSED_WITHOUT_SUBMISSION','Closed without submission']])}
      {select('stage','Detailed stage',stages.map(s=>[s,label(s)]))}
      {select('relevance','Relevance',[['confirmed','Confirmed'],['unclassified','Unclassified'],['unmapped','School unmapped'],['dismissed','Manually not relevant'],['ad-hoc','Ad-hoc']])}
      {select('exception','Exceptions',[['matched-unallocated','Matched researchers but no allocation'],['untouched','Relevant call untouched'],['approached-unallocated','Researchers approached but no allocation'],['unallocated-no-matches','Matching completed with no suitable researcher'],['no-next-action','Pending application without next action'],['overdue','Overdue'],['no-follow-up','No faculty follow-up'],['missing-submission-proof','Missing submission evidence'],['missing-deadline','Missing agency deadline']])}
      {select('horizon','Deadline window',[['7','Within 7 days / overdue'],['14','Within 14 days / overdue'],['21','Within 21 days / overdue'],['30','Within 30 days / overdue']])}
      {select('waitingWith','Waiting with',['FACULTY','DSR','REVIEWER','APPROVER','AGENCY'].map(s=>[s,label(s)]))}
      {select('responsibilityType','Responsibility',[['ORIGIN_REVIEW','Origin-school intake review'],['MATCHED_FOLLOW_UP','Matched-school follow-up']])}
      {select('actionClass','Action class',[['DSR_ACTION_REQUIRED','DSR action required'],['WAITING_ON_FACULTY','Waiting on faculty'],['WAITING_ON_REVIEWER_APPROVER','Waiting on reviewer / approver'],['WAITING_ON_AGENCY','Waiting on agency'],['SYSTEM_PROCESSING','System processing'],['COMPLETED','Completed'],['DATA_GAP','Data gap']])}
      {select('ageDays','Age',[['3','3+ days since activity'],['7','7+ days since activity'],['14','14+ days since activity'],['30','30+ days since activity']])}
    </div></details><p className="nk-sub">{filters.mode==='pending'?'Outstanding applications and open unallocated opportunities, including older work.':filters.mode==='portfolio'?'Every currently mapped call–school opportunity as of the report date. The selected period does not hide older or resolved calls.':filters.mode==='cohort'?'Opportunities first evidenced in the selected period, followed to their latest outcome. Unknown first-seen dates are excluded, not guessed.':'Applications with allocations, external faculty contacts, submissions or action completions in the selected period. Activity totals below count events within that period.'}</p></div>
    <div className="flex justify-between gap-3 text-xs"><span>{data?`${data.windowLabel} · India time · Report as of ${new Date(data.asOf).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}`:''}</span><div className="flex gap-2"><HelpButton help="Recalculate this report from the latest saved activity while keeping your filters." className="nk-btn-secondary nk-btn-xs" onClick={refresh}>Refresh</HelpButton><HelpButton help="Download every filtered record and summary as CSV, not only the visible page." className="nk-btn-secondary nk-btn-xs" onClick={()=>exportReport('csv')}>Export all CSV</HelpButton><HelpButton help="Download every filtered record and summary as a multi-sheet Excel workbook." className="nk-btn-secondary nk-btn-xs" onClick={()=>exportReport('xlsx')}>Export all XLSX</HelpButton></div></div>
    {(error||exportError)&&<p role="alert" className="text-red-700">{error||exportError}</p>}
    {loading&&<p role="status" className="nk-sub">Loading report…</p>}
    {data&&!error&&<>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Call–school opportunities',data.totals.callSchoolOpportunities],['Calls acted on',data.totals.actedOn],['Relevant calls untouched',data.totals.untouched],['Matched, not allocated',data.totals.matchedUnallocated],['Formal allocations',data.totals.allocated],['Pending without next action',data.totals.noNextAction],['Recorded submissions',data.totals.submitted],['Verified submissions',data.totals.verified],['Needs attention',data.totals.needsAttention]].map(([title,value])=><div className="nk-panel p-3" key={title}><p className="nk-sub">{title}</p><p className="text-2xl font-semibold">{value}</p></div>)}</div>
      <p className="nk-sub">Submission split: {data.totals.allocatedSubmissions} allocated + {data.totals.independentSubmissions} independent. Period activity: {data.activity.allocations} allocations · {data.activity.independent} independent applications · {data.activity.contacts} faculty contact events · {data.activity.submissions} submissions.</p>
      {['member-funnel','school-coverage','opportunity-gaps'].includes(view)&&<p className="rounded border border-cobalt-100 bg-cobalt-50 p-3 text-xs text-cobalt-900"><strong>Action coverage definition:</strong> a mapped call is acted on when there is a formal allocation or independent application, a researcher has been reviewed, an external faculty contact is recorded, a named action exists, or a structured no-uptake decision is saved. Automated matching by itself does not count as human action.</p>}
      <div className="rounded border border-amber-200 bg-amber-50 p-3 text-xs">Data quality: {data.totals.unclassified} unclassified call–school records · {data.totals.unmapped} unmapped · {data.quality.unknownStageDates} application stage-entry dates not recorded · {data.quality.incompleteMatchingOpportunities} relevant opportunities without a complete matching run. {!data.quality.matchingComplete&&'Recorded matches must not be read as a complete count of all suitable faculty.'} Historical matches labelled inferred: {data.quality.inferredMatches}. {data.portfolio==='deputy'&&'Deputy operational view only; do not add these totals to primary accountability.'}</div>
      {view==='workbench'&&<Workbench rows={data.rows||[]} headSummary={data.headSummary} lens={data.lens} query={base} people={data.options.people} schools={data.options.schools} revision={revision} refresh={refresh}/>}
      {['member-funnel','school-coverage'].includes(view)&&<section className="nk-panel"><Table head={['Primary DSR member','Schools','Mapped relevant calls','Acted on','Untouched','Matched, not allocated','Allocated / independent','Followed up','Submitted / verified','Needs attention']}>
        {(data.members||[]).map(m=><Fragment key={m.id}><tr><Cell><button title="Expand this member to see the school-wise split without leaving the report." className="text-cobalt-700 font-medium" aria-expanded={!!expanded[m.id]} onClick={()=>toggle(m.id)}>{expanded[m.id]?'−':'+'} {m.name}</button></Cell><Cell>{m.childCount}</Cell><Cell>{m.totals.callSchoolOpportunities}</Cell><Cell>{m.totals.actedOn}</Cell><Cell>{m.totals.untouched}</Cell><Cell>{m.totals.matchedUnallocated}</Cell><Cell>{m.totals.allocated} / {m.totals.independent}</Cell><Cell>{m.totals.followedUp} allocations</Cell><Cell>{m.totals.submitted} / {m.totals.verified}</Cell><Cell>{m.totals.needsAttention}</Cell></tr>
          {expanded[m.id]&&<tr><td colSpan={10} className="p-4 bg-nickel-50"><Table head={['School','Mapped calls','Acted on','Untouched','Matched, not allocated','Matches','Allocated / independent','Pending','Submitted','Overdue']}>
            {m.schools.map(s=><Fragment key={s.id}><tr><Cell><button title="Expand this school to see each mapped call, deadline and action status." className="text-cobalt-700" aria-expanded={!!expanded[s.id]} onClick={()=>toggle(s.id)}>{expanded[s.id]?'−':'+'} {s.name}</button>{s.isUnmapped&&<p className="text-amber-700">School mapping incomplete</p>}</Cell>{['relevant','actedOn','untouched','matchedUnallocated','matches','allocated','pending','submitted','overdue'].map(key=><Cell key={key}>{(s as any).totals[key]}{key==='allocated'?` / ${(s as any).totals.independent}`:''}</Cell>)}</tr>
              {expanded[s.id]&&<tr><td colSpan={10} className="p-3"><SchoolCalls reportView={view} schoolId={s.id} memberId={m.id} query={detailQuery} revision={revision} onOpen={setDetail} refresh={refresh}/></td></tr>}
            </Fragment>)}
          </Table></td></tr>}
        </Fragment>)}
      </Table>{!data.members?.length&&<p className="p-5 nk-sub">No accessible school portfolios match these filters.</p>}</section>}
      {view==='opportunity-gaps'&&<OpportunityGaps reportView={view} rows={data.rows||[]} query={base} people={data.options.people} revision={revision} refresh={refresh}/>}
      {['pending','deadline-risk','outcomes'].includes(view)&&<section className="nk-panel">
        {view==='pending'?['FACULTY','DSR','REVIEWER','APPROVER','AGENCY','UNASSIGNED'].map(group=>{const apps=(data.rows||[]).filter(a=>(a.nextAction?.waiting_with||'UNASSIGNED')===group);return apps.length?<div key={group}><h2 className="p-3 font-medium">Waiting with {label(group)}</h2><AppTable apps={apps} onOpen={setDetail}/></div>:null}):<AppTable apps={data.rows||[]} onOpen={setDetail}/>}
        <Pager page={page} total={data.total} onChange={setPage}/>
        {!!data.unallocated?.length&&<div className="p-3"><h2 className="font-medium">Relevant opportunities with no formal allocation</h2>{data.unallocated.map(c=><details key={`${c.schoolId}:${c.id}`} className="border-t py-3"><summary className="cursor-pointer" title="Expand to see matched researchers and resolve this unallocated opportunity.">{c.title} · {c.matchedFaculty} recorded matches · {c.actionState==='UNTOUCHED'?'untouched':'action recorded'} · agency {date(c.deadline)} · {deadlineCopy(c)}</summary><div className="space-y-3 pt-3"><MatchRows reportView={view} query={base} call={c} revision={revision} refresh={refresh}/><OpportunityActions call={c} people={data.options.people} query={base} refresh={refresh}/></div></details>)}</div>}
      </section>}
      {view==='coverage'&&<section className="nk-panel"><Table head={['Faculty','Engagement / profile','Suitable opportunities','Approached','Never approached','Allocations','Active applications','Submitted']}>
        {(data.rows||[]).map(p=><tr key={p.id}><Cell><button className="font-medium text-cobalt-700 hover:underline" onClick={()=>setPersonDetail({id:p.id,name:p.name})}>{p.name}</button><p className="nk-sub">Open matching calls</p></Cell><Cell>{label(p.engagement)}<p className={p.profileReady?'nk-sub':'text-amber-700'}>{p.profileReady?'Profile ready':'Research profile incomplete'}</p></Cell>{[p.suitableOpportunities,p.approached,p.neverApproached,p.allocations,p.active,p.submitted].map((v,i)=><Cell key={i}>{v}</Cell>)}</tr>)}
      </Table><p className="p-3 nk-sub">Complete accessible school roster. Suitable opportunities use the current match projection; workload counts are context, not an overload judgement.</p><Pager page={page} total={data.total} onChange={setPage}/></section>}
      {view==='performance'&&<div className="space-y-3">{(data.rows||[]).map(p=><section className="nk-panel p-4" key={p.id}><h2 className="font-semibold">{p.name}</h2><div className="grid gap-4 md:grid-cols-3 mt-3"><div><h3 className="font-medium">Workload</h3><p>{p.workload.callSchoolOpportunities} mapped opportunities · {p.workload.outstanding} outstanding applications</p><p>{p.workload.untouched} untouched · {p.workload.matchedUnallocated} matched but unallocated</p><p>{p.inheritedBacklog ?? 'Not recorded'} inherited backlog</p></div><div><h3 className="font-medium">Execution</h3><p>Opportunity action coverage: <Ratio value={p.opportunityActionCoverage}/></p><p>Faculty contact coverage: <Ratio value={p.facultyContactCoverage}/></p><p>Timely completed actions: <Ratio value={p.timelyActions}/></p><p>Allocation median: {p.medianAllocationDays?.toFixed(1)??'—'} days ({p.allocationSample} completed allocations)</p><p>First faculty contact after allocation: {p.medianFirstContactDays?.toFixed(1)??'—'} days ({p.firstContactSample} cases; {p.awaitingContact} still awaiting)</p><p>{p.performedContacts} contact events performed by this member</p></div><div><h3 className="font-medium">Results</h3><p>Cohort submission conversion: <Ratio value={p.submissionConversion}/></p><p>{p.independentSubmissions} independent submissions (separate)</p><p>Funding success: <Ratio value={p.fundingSuccess}/> · {p.undecided} undecided</p><p>Submissions by submission date: {p.periodSubmissions} vs {p.previousPeriodSubmissions} previous equal-length period</p>{Object.entries(p.money as Record<string,{requested:number;sanctioned:number}>).map(([currency,m])=><p key={currency}>{currency}: requested {m.requested.toLocaleString()} · sanctioned {m.sanctioned.toLocaleString()}</p>)}</div></div></section>)}</div>}
      {view==='weekly-review'&&<section className="nk-panel p-4"><h2 className="font-semibold">Backlog movement</h2><p className="nk-sub">{data.definition}</p>{!data.complete&&<p className="text-amber-700 my-3">{data.note}</p>}<Table head={['Member','Opening','New','Reopened','Transferred in','Resolved','Transferred out','Closing','Reconciled']}>
        {(data.members||[]).map((m:any)=><tr key={m.id}>{[m.name,m.opening,m.newWork,m.reopened,m.transfersIn,m.resolved,m.transfersOut,m.closing,m.reconciled===null?'Incomplete':m.reconciled?'Yes':'Check required'].map((v,i)=><Cell key={i}>{v}</Cell>)}</tr>)}
      </Table><h3 className="font-medium mt-4">Urgent decisions and blockers</h3>{data.urgentActions?.map(a=><p key={a.id} className="mt-2"><button title={a.application_id?'Open the application and resolve this urgent action.':'This call-level action has no application detail panel.'} className="text-cobalt-700" disabled={!a.application_id} onClick={()=>setDetail(a.application_id)}>{a.title}</button> · {a.owner_name} · {date(a.due_at)} · {a.blocker||'Overdue action'}</p>)}<h3 className="font-medium mt-4">Urgent untouched or unallocated opportunities</h3>{data.urgentOpportunities?.map(c=><p key={`${c.schoolId}:${c.id}`} className="mt-2">{c.memberName} · {c.schoolName} · {c.title} · {c.matchedFaculty} matches · {c.gaps.map((g:string)=>label(g)).join(', ')} · deadline {date(c.deadline)}</p>)}{!data.urgentOpportunities?.length&&<p className="nk-sub">No urgent opportunity-action gaps in this view.</p>}</section>}
    </>}
    {detail&&<ApplicationPanel id={detail} query={base} onClose={closeDetail} onSaved={refresh}/>}
    {personDetail&&<PersonCallsPanel person={personDetail} includeExpired={filters.includeExpired==='true'} onClose={()=>setPersonDetail(null)}/>}
  </div>
}

function Workbench({rows,headSummary,lens,query,people,schools,revision,refresh}:{rows:any[];headSummary:any;lens:string;query:string;people:Person[];schools:Array<{id:string;name:string}>;revision:number;refresh:()=>void}) {
  const [open,setOpen]=useState<Record<string,boolean>>({})
  const queues=[['ACTION_OVERDUE','Action overdue'],['CLOSING_SOON','Closing soon and unresolved'],['NEW_TO_REVIEW','New calls to review'],['WAITING_ON_OTHERS','Waiting on others'],['IN_PROGRESS','In progress'],['DATA_ROUTING','Data or routing problems'],['COMPLETED','Completed']]
  return <div className="space-y-4">
    <section className="rounded border border-cobalt-200 bg-cobalt-50 p-4"><h2 className="font-semibold">{lens==='department'?'Department control room':'My school desk'}</h2><p className="nk-sub">{lens==='department'?'Exceptions are ranked by urgency and retain the accountable member, waiting party and corrective action.':'Your primary-school responsibilities, ordered by what needs attention first.'}</p>
      {headSummary&&<div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">{[['Overdue',headSummary.actionOverdue],['Closing soon',headSummary.closingSoon],['New review',headSummary.newToReview],['Waiting',headSummary.waitingOnOthers],['Data / routing',headSummary.dataRouting],['Never assigned',headSummary.peopleNeverAssigned],['Uncovered schools',headSummary.uncoveredSchools],['Corrective actions overdue',headSummary.correctiveActions?.overdue]].map(([name,value])=><div className="rounded bg-white p-3" key={String(name)}><p className="nk-sub">{name}</p><p className="text-xl font-semibold">{value??0}</p></div>)}</div>}
    </section>
    {queues.map(([code,title])=>{const items=rows.filter(row=>row.responsibility.queue===code);if(!items.length)return null;return <section className="nk-panel" key={code}><div className="nk-panel-head"><h2 className="nk-title">{title}</h2><span className="nk-badge">{items.length}</span></div>{items.map(row=>{const key=row.workItemId;return <div className="border-t border-nickel-100 p-4" key={key}><div className="flex flex-wrap items-start justify-between gap-3"><div><button className="text-left font-medium text-cobalt-700 hover:underline" onClick={()=>setOpen(value=>({...value,[key]:!value[key]}))}>{open[key]?'−':'+'} {row.title}</button><p className="nk-sub">{row.schoolName} · {row.memberName} · {row.agency||'Agency not recorded'} · deadline {date(row.deadline)}</p><p className="mt-1 text-sm">{row.responsibility.responsibilityType==='ORIGIN_REVIEW'?'Origin-school intake review':'Matched-school opportunity follow-up'} · {label(row.responsibility.actionClass)}</p><p className="nk-sub">{row.matchedFaculty} matching researcher(s) · {row.allocated} allocated · {row.approached} approached · {row.submitted} submitted</p></div><div className="text-right text-sm"><p>{row.responsibility.nextAction?.title||'Next action not confirmed'}</p><p className="nk-sub">{row.responsibility.nextAction?.owner_name||row.memberName} · due {date(row.responsibility.nextAction?.due_at)}</p>{row.isExpired&&<span className="nk-badge nk-badge-danger">Expired{row.retainedBecauseLiveWork?' · live work retained':''}</span>}</div></div>{open[key]&&<div className="mt-4 space-y-4 rounded bg-nickel-50 p-4"><p className="text-sm"><strong>Why visible:</strong> {(row.visibilityReasons||[]).map(label).join(' · ')||'Recorded work'} · <strong>Last action:</strong> {row.lastAction?`${date(row.lastAction.at)} by ${row.lastAction.by}`:'not recorded'} · <strong>Silent:</strong> {row.responsibility.daysSinceActivity??'unknown'} days</p>{lens==='department'&&!row.origin_school_id&&<OriginCorrection callId={row.callId} schools={schools} onSaved={refresh}/>}<MatchRows reportView="workbench" query={query} call={row as Call} revision={revision} refresh={refresh}/><OpportunityActions call={row as Call} people={people} query={query} refresh={refresh}/></div>}</div>})}</section>})}
    {!rows.length&&<section className="nk-panel p-6 text-center nk-sub">No responsibilities match the selected filters.</section>}
  </div>
}

function OriginCorrection({callId,schools,onSaved}:{callId:string;schools:Array<{id:string;name:string}>;onSaved:()=>void}) {
  const {authFetch}=useAuth();const [error,setError]=useState('')
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const response=await authFetch(`/api/funding-dept/calls/${encodeURIComponent(callId)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({originSchoolId:data.get('school'),reason:data.get('reason')})});const body=await response.json();if(!response.ok){setError(body.error);return}onSaved()}
  return <form onSubmit={save} className="flex flex-wrap items-end gap-2 rounded border border-amber-200 bg-amber-50 p-3"><label className="text-xs">Correct origin school<select name="school" required className={`${field} block`}><option value="">Select school</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-xs">Reason<input name="reason" minLength={3} required className={`${field} block`}/></label><button className="nk-btn-secondary nk-btn-xs">Save correction</button>{error&&<p className="text-red-700">{error}</p>}</form>
}

function PersonCallsPanel({person,includeExpired,onClose}:{person:{id:string;name:string};includeExpired:boolean;onClose:()=>void}) {
  const {authFetch}=useAuth();const [data,setData]=useState<any>(null);const [error,setError]=useState('')
  useEffect(()=>{authFetch(`/api/funding-dept/reports/faculty/${encodeURIComponent(person.id)}/calls?includeExpired=${includeExpired}`).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.error);setData(body)}).catch(e=>setError(e.message))},[authFetch,person.id,includeExpired])
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/30"><section role="dialog" aria-modal="true" className="h-full w-full max-w-3xl overflow-y-auto bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">{person.name}</h2><p className="nk-sub">Calls matching this researcher</p></div><button className="nk-btn-secondary nk-btn-sm" onClick={onClose}>Close</button></div>{error&&<p className="mt-4 text-red-700">{error}</p>}{!data&&!error&&<p className="mt-4 nk-sub">Loading matching calls…</p>}{data&&<div className="mt-4 space-y-3">{data.readiness?.isUnprofiled&&<p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm">This researcher has no usable profile evidence. Complete their research areas or keywords before treating zero matches as final.</p>}{data.calls.map((call:any)=><div className="rounded border p-4" key={call.id}><div className="flex justify-between gap-3"><div><Link className="font-medium text-cobalt-700 hover:underline" href={`/funding-dept/calls/${call.id}`}>{call.title||'Untitled call'}</Link><p className="nk-sub">{call.agencyName||'Agency not recorded'} · {date(call.closesAt)}</p></div><span className="nk-badge">{label(call.tier)} · {Math.round(call.score*100)}%</span></div><p className="mt-2 text-sm">Matched through {label(call.source)}{call.matchedOn?` · ${call.matchedOn}`:''}</p><p className="nk-sub">{call.assignment?`Assignment: ${label(call.assignment.status)}`:call.candidate?`Review: ${label(call.candidate.status)}`:'Not yet reviewed or assigned'}</p></div>)}{!data.calls.length&&<p className="nk-sub">No matching {includeExpired?'':'active '}calls were found.</p>}</div>}</section></div>
}

function OpportunityGaps({reportView,rows,query,people,revision,refresh}:{reportView:string;rows:any[];query:string;people:Person[];revision:number;refresh:()=>void}) {
  const [open,setOpen]=useState<Record<string,boolean>>({})
  return <section className="nk-panel"><Table head={['DSR member','School','Mapped call','Researchers','Allocation','Action coverage','Deadline','Gap']}>
    {rows.map(c=>{const key=`${c.schoolId}:${c.id}`;return <Fragment key={key}><tr><Cell>{c.memberName}</Cell><Cell>{c.schoolName}</Cell><Cell><button title="Expand this opportunity to see matched researchers and resolve its next action." className="text-left font-medium text-cobalt-700 hover:underline" aria-expanded={!!open[key]} onClick={()=>setOpen(value=>({...value,[key]:!value[key]}))}>{open[key]?'−':'+'} {c.title}</button><p className="nk-sub">{c.agency||'Agency not recorded'}</p></Cell><Cell>{c.matchedFaculty} matched<p className="nk-sub">{c.considered} reviewed · {c.approached} approached</p></Cell><Cell>{c.unallocated?'No formal allocation':`${c.allocated} formal`}<p className="nk-sub">{c.independent} independent</p></Cell><Cell>{c.actedOn?'Acted on':'Untouched'}<p className="nk-sub">{c.touchSignals.map((s:string)=>label(s)).join(' · ')||'No recorded human action'}</p></Cell><Cell>{date(c.deadline)}<p className={c.daysToDeadline<0?'text-red-700':'nk-sub'}>{deadlineCopy(c)}</p></Cell><Cell>{c.gaps.map((g:string)=><span className="nk-badge nk-badge-warn mr-1" key={g}>{label(g)}</span>)}</Cell></tr>
      {open[key]&&<tr><td colSpan={8} className="bg-nickel-50 p-4"><div className="space-y-4"><MatchRows reportView={reportView} query={query} call={c as Call} revision={revision} refresh={refresh}/><OpportunityActions call={c as Call} people={people} query={query} refresh={refresh}/></div></td></tr>}
    </Fragment>})}
    {!rows.length&&<tr><td colSpan={8} className="p-6 text-center nk-sub">No opportunity-action gaps match these filters.</td></tr>}
  </Table></section>
}

function SchoolCalls({reportView,schoolId,memberId,query,revision,onOpen,refresh}:{reportView:string;schoolId:string;memberId:string;query:string;revision:number;onOpen:(id:string)=>void;refresh:()=>void}) {
  const [page,setPage]=useState(1);const [open,setOpen]=useState<Record<string,boolean>>({});const q=new URLSearchParams(query);q.set('drillSchoolId',schoolId);if(q.get('portfolio')!=='deputy')q.set('drillMemberId',memberId);q.set('level','calls');q.set('page',String(page))
  const {data,error,loading}=useReport(`/api/funding-dept/reports/${reportView}?${q}`,revision)
  useEffect(()=>setPage(1),[query])
  return <div className="bg-white rounded border border-nickel-200">{error&&<p role="alert">{error}</p>}{loading&&<p className="p-3 nk-sub">Loading calls…</p>}{data?.rows?.map((c:Call)=><div key={c.id} className="border-b p-3"><button title="Expand this call to see allocations, matched researchers and remedies." className="text-cobalt-700 text-left font-medium" aria-expanded={!!open[c.id]} onClick={()=>setOpen(o=>({...o,[c.id]:!o[c.id]}))}>{open[c.id]?'−':'+'} {c.title}</button><p className="nk-sub">{c.agency} · Agency deadline {date(c.deadline)} · {deadlineCopy(c)} · {label(c.quality)} · {c.reason||'Reason not recorded'}</p><p className="text-sm mt-2">{c.matchedFaculty} saved matches ({label(c.matchCompleteness)}) · {c.considered} reviewed · {c.approached} approached · {c.allocated} allocations + {c.independent} independent · {c.pending} pending · {c.submitted} submitted · {c.overdue} overdue</p><p className="nk-sub">Action coverage: {c.actedOn?'Acted on':'Untouched'}{c.touchSignals.length?` · ${c.touchSignals.map(label).join(' · ')}`:''}. Last action: {c.lastAction?`${date(c.lastAction.at)} · Performed by ${c.lastAction.by}`:'Not recorded'}</p>{c.unallocated&&<p className="text-amber-700 text-sm">Relevant opportunity with nobody formally allocated.{c.matchedUnallocated?` ${c.matchedFaculty} matched researcher(s) are waiting for allocation.`:''}</p>}{c.missedUnallocatedNoSubmission&&<p className="text-red-700 text-sm font-medium">Missed without allocation or submission · {c.missedExplanationStatus==='EXPLAINED'?'reason recorded':'explanation still required'}</p>}
    <p className="text-sm">{c.followedUp} followed up · {c.verified} verified · {c.declined} declined · {c.lapsed} lapsed</p>
    {open[c.id]&&<div className="mt-3 space-y-3"><CallApplications reportView={reportView} query={q.toString()} callId={c.id} revision={revision} onOpen={onOpen}/><OpportunityActions call={c} people={data.options.people} query={query} refresh={refresh}/><MatchRows reportView={reportView} query={q.toString()} call={c} revision={revision} refresh={refresh}/></div>}
  </div>)}{data&&!data.rows?.length&&<p className="p-4 nk-sub">No calls match this view. Unknown first-seen dates are excluded from cohorts.</p>}<Pager page={page} total={data?.total} onChange={setPage}/></div>
}
function CallApplications({reportView,query,callId,revision,onOpen}:{reportView:string;query:string;callId:string;revision:number;onOpen:(id:string)=>void}) {const [page,setPage]=useState(1);const q=new URLSearchParams(query);q.set('drillCallId',callId);q.set('level','applications');q.set('page',String(page));const {data,error}=useReport(`/api/funding-dept/reports/${reportView}?${q}`,revision);return <>{error&&<p role="alert">{error}</p>}<AppTable apps={data?.rows||[]} onOpen={onOpen}/><Pager page={page} total={data?.total} onChange={setPage}/></>}
function MatchRows({reportView,query,call,revision,refresh}:{reportView:string;query:string;call:Call;revision:number;refresh:()=>void}) {const [show,setShow]=useState(false);return <details onToggle={e=>setShow(e.currentTarget.open)}><summary title="Expand the saved matching evidence and take action for an individual researcher." className="cursor-pointer text-sm">Matched researchers and matching evidence</summary>{show&&<MatchPage reportView={reportView} query={query} call={call} revision={revision} refresh={refresh}/>}</details>}
function MatchPage({reportView,query,call,revision,refresh}:{reportView:string;query:string;call:Call;revision:number;refresh:()=>void}) {
  const {authFetch}=useAuth();const {me}=useFundingDeptMe();const [page,setPage]=useState(1);const [assign,setAssign]=useState<any|null>(null);const [actionError,setActionError]=useState('');const [busy,setBusy]=useState('')
  const q=new URLSearchParams(query);q.set('drillCallId',call.id);if(call.schoolId)q.set('drillSchoolId',call.schoolId);q.set('level','matches');q.set('page',String(page));const {data,error}=useReport(`/api/funding-dept/reports/${reportView}?${q}`,revision)
  async function approached(m:any){const note=window.prompt(`Optional note about approaching ${m.faculty?.name||'this researcher'}:`);if(note===null)return;setBusy(m.id);setActionError('');try{const response=await authFetch(`/api/funding-dept/calls/${call.id}/candidates`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:m.faculty?.id||m.user_id,status:'APPROACHED',note:note.trim()||null,matchScore:m.match_score??undefined,matchTier:m.match_tier??undefined})});const json=await response.json();if(!response.ok)throw Error(json.error||'Could not record the approach.');refresh()}catch(e){setActionError((e as Error).message)}finally{setBusy('')}}
  return <>{(error||actionError)&&<p role="alert" className="text-red-700">{error||actionError}</p>}<Table head={['Faculty','Allocation status','Score','Reason','Source / version','First seen','Resolve']}>
    {data?.rows?.map(m=>{const pending=m.allocationStatus==='PENDING_ALLOCATION';const person={userId:m.faculty?.id||m.user_id,name:m.faculty?.name||m.user_id,score:m.match_score??null,matchTier:m.match_tier??null};return <tr key={m.id}><Cell>{person.name}</Cell><Cell>{pending?<span className="nk-badge nk-badge-warn">Pending allocation</span>:label(m.allocationStatus)}{m.candidateStatus&&<p className="nk-sub">{label(m.candidateStatus)}</p>}{m.applicationWorkState&&<p className="nk-sub">{label(m.applicationWorkState)}</p>}</Cell><Cell>{m.match_score??'Unknown'}</Cell><Cell>{m.match_reason||'Not recorded'}</Cell><Cell>{m.source} / {m.source_version||'Not recorded'} {m.inferred?'· inferred':''}</Cell><Cell>{date(m.first_seen_at)}</Cell><Cell>{pending&&me.capabilities.canAssign?<div className="flex flex-wrap gap-2"><HelpButton help="Create a formal allocation for this researcher and notify them by app and email." className="nk-btn-primary nk-btn-xs" onClick={()=>setAssign(person)}>Assign and notify</HelpButton><HelpButton help="Record that this researcher was approached. This is shortlist activity, not a faculty follow-up on an allocation." className="nk-btn-secondary nk-btn-xs" disabled={busy===m.id} onClick={()=>approached(m)}>{busy===m.id?'Saving…':'Mark approached'}</HelpButton></div>:pending?<ActionEditor schoolId={call.schoolId} callId={call.id} people={data?.options?.people||[]} suggested={call.suggestedActionOwner} query={query} onSaved={refresh} buttonLabel="Request allocation" help="Create a named action asking the accountable officer or head to review this researcher for allocation." defaults={{title:`Review and allocate ${person.name} for ${call.title}`,waitingWith:'DSR',deadlineType:'ACTION'}}/>:<span className="nk-sub">Allocation action already recorded</span>}</Cell></tr>})}
    {!data?.rows?.length&&<tr><td colSpan={7} className="p-4 nk-sub">No saved researcher matches are available. Review matching completeness before recording no suitable faculty.</td></tr>}
  </Table><Pager page={page} total={data?.total} onChange={setPage}/>{assign&&<AssignDialog callId={call.id} callTitle={call.title} callCloseDate={call.deadline} person={assign} onClose={()=>setAssign(null)} onAssigned={()=>{setAssign(null);refresh()}}/>}</>}

function ActionEditor({schoolId,applicationId,callId,people,query,existing,suggested,onSaved,buttonLabel,help,defaults}:{schoolId:string;applicationId?:string|null;callId?:string|null;people:Person[];query:string;existing?:Action;suggested?:Person|null;onSaved:()=>void;buttonLabel?:string;help?:string;defaults?:{title?:string;waitingWith?:string;deadlineType?:string}}) {
  const {authFetch}=useAuth();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [show,setShow]=useState(false)
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const data=new FormData(form);try{const due=data.get('dueAt') as string;const response=await authFetch(`/api/funding-dept/actions?${query}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({schoolId,applicationId,callId,id:existing?.id,version:existing?.version,title:data.get('title'),ownerUserId:data.get('owner'),waitingWith:data.get('waiting'),dueAt:due?new Date(`${due}:00+05:30`).toISOString():null,deadlineType:data.get('deadlineType'),blocker:data.get('blocker')||null,reason:data.get('reason')||undefined,resolutionNote:data.get('resolutionNote')||undefined,isNext:data.get('next')==='on',status:data.get('status')||'OPEN'})});const json=await response.json();if(!response.ok)throw Error(json.error);setShow(false);onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const trigger=buttonLabel||(existing?'Edit / complete / reopen':'Add action')
  return <div><HelpButton help={help||(existing?'Update ownership, timing, status or blocker while preserving the action history.':'Create a named next action with an accountable owner and due date.')} className="nk-btn-secondary nk-btn-xs" onClick={()=>setShow(s=>!s)}>{trigger}</HelpButton>{show&&<form onSubmit={save} className="grid gap-3 rounded border p-3 mt-2 sm:grid-cols-2">
    <label className="text-xs">Action<input name="title" required maxLength={1000} defaultValue={existing?.title||defaults?.title} className={`${field} block w-full`}/></label>
    <label className="text-xs">Confirmed named owner<select name="owner" required defaultValue={existing?.owner_user_id||''} className={`${field} block w-full`}><option value="">Select and confirm a person</option>{people.map(p=><option key={p.id} value={p.id}>{p.name||p.id}</option>)}</select>{suggested&&<span>Suggested: {suggested.name}. Please confirm explicitly.</span>}</label>
    <label className="text-xs">Waiting with<select name="waiting" required defaultValue={existing?.waiting_with||defaults?.waitingWith||''} className={`${field} block w-full`}><option value="">Choose category</option>{['FACULTY','DSR','REVIEWER','APPROVER','AGENCY'].map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="text-xs">Action due (India time)<input name="dueAt" type="datetime-local" defaultValue={existing?.due_at?new Date(new Date(existing.due_at).getTime()+330*60000).toISOString().slice(0,16):''} className={`${field} block w-full`}/></label>
    <label className="text-xs">Deadline type<select name="deadlineType" defaultValue={existing?.deadline_type||defaults?.deadlineType||'ACTION'} className={`${field} block w-full`}>{['ACTION','AGENCY','INTERNAL_REVIEW','REVISION'].map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="text-xs">Status<select name="status" defaultValue={existing?.status||'OPEN'} className={`${field} block w-full`}><option value="OPEN">Open / reopen</option><option value="ACKNOWLEDGED">Acknowledged / working</option><option value="DONE">Completed</option><option value="CANCELLED">Cancelled</option></select></label>
    <label className="text-xs">Blocker<input name="blocker" defaultValue={existing?.blocker||''} className={`${field} block w-full`}/></label>
    <label className="text-xs">Reason (required for reassignment or extension)<input name="reason" className={`${field} block w-full`}/></label>
    <label className="text-xs">Resolution note (required to complete or cancel)<input name="resolutionNote" defaultValue={(existing as any)?.resolution_note||''} className={`${field} block w-full`}/></label>
    <label className="text-sm"><input name="next" type="checkbox" defaultChecked={existing?.is_next??true}/> Designate as next action</label>
    <div className="flex gap-2"><HelpButton help="Save this action and its named ownership to the audit history." className="nk-btn-primary nk-btn-sm" disabled={busy}>{busy?'Saving…':'Save action'}</HelpButton><HelpButton help="Close this form without saving changes." type="button" className="nk-btn-secondary nk-btn-sm" onClick={()=>setShow(false)}>Cancel</HelpButton></div>{error&&<p role="alert" className="text-red-700 sm:col-span-2">{error}</p>}
  </form>}</div>
}
function CallFollowUpForm({call,onLogged}:{call:Call;onLogged:()=>void}) {const [show,setShow]=useState(false);return <details onToggle={e=>setShow(e.currentTarget.open)}><summary title="Record internal coordination or an external call, email or meeting before a formal allocation exists." className="cursor-pointer text-sm">Record call-level coordination or contact</summary>{show&&<FollowUpPanel target={{callId:call.id,orgUnitId:call.schoolId}} formOnly onLogged={onLogged}/>}</details>}
function OpportunityActions({call,people,query,refresh}:{call:Call;people:Person[];query:string;refresh:()=>void}) {
  const {authFetch}=useAuth();const [error,setError]=useState('');if(call.id.startsWith('adhoc:'))return null
  async function disposition(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setError('');try{const response=await authFetch(`/api/funding-dept/actions?${query}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'disposition',schoolId:call.schoolId,callId:call.id,disposition:data.get('disposition'),reason:data.get('reason')||undefined})});if(!response.ok)throw Error((await response.json()).error);refresh()}catch(e){setError((e as Error).message)}}
  const defaults=call.missedUnallocatedNoSubmission?{title:`Check agency extension or close missed opportunity: ${call.title}`,waitingWith:'DSR',deadlineType:'AGENCY'}:call.matchCompleteness!=='COMPLETE'?{title:`Complete researcher matching review for ${call.title}`,waitingWith:'DSR',deadlineType:'ACTION'}:undefined
  return <div className="space-y-3"><div className="rounded border border-cobalt-100 bg-cobalt-50 p-3 text-sm"><h4 className="font-medium">Recommended way forward</h4>{call.missedUnallocatedNoSubmission?<p>Deadline passed with no allocation or submission. Check whether the agency extended the deadline; otherwise record why it was missed and close the accountability loop.</p>:call.matchedFaculty>0&&call.unallocated?<p>Review the matched researchers below, record who was approached, and allocate a confirmed researcher. If allocation is outside your authority, assign the decision to the primary officer or head.</p>:call.matchCompleteness!=='COMPLETE'?<p>Matching is incomplete. Complete the researcher review before concluding that nobody is suitable.</p>:call.unallocated?<p>No suitable researcher is recorded. Save a structured no-uptake reason or create a named action for further review.</p>:<p>Open the application above to record faculty follow-up, submission evidence or its next action.</p>}<Link title="Open the full call workspace in a new tab while preserving this report." target="_blank" href={`/funding-dept/calls/${encodeURIComponent(call.id)}?school=${encodeURIComponent(call.schoolId)}`} className="mt-2 inline-block text-cobalt-700 underline">Open full call workspace</Link></div><h4 className="text-sm font-medium">Opportunity actions</h4>{call.actions.map(a=><div key={a.id} className="text-sm">{a.is_next?'Next: ':''}{a.title} · {a.owner_name} · {label(a.status)} · {date(a.due_at)}<ActionEditor schoolId={call.schoolId} callId={call.id} people={people} query={query} existing={a} onSaved={refresh}/></div>)}<ActionEditor schoolId={call.schoolId} callId={call.id} people={people} suggested={call.suggestedActionOwner} query={query} onSaved={refresh} buttonLabel={call.missedUnallocatedNoSubmission?'Create recovery action':undefined} help={call.missedUnallocatedNoSubmission?'Assign someone to check for an extension, escalate the miss, or complete the closure record.':undefined} defaults={defaults}/>
    <CallFollowUpForm call={call} onLogged={refresh}/>
    <form onSubmit={disposition} className="flex flex-wrap items-end gap-2"><label className="text-xs">No uptake reason<select name="disposition" className={`${field} block`} defaultValue={call.disposition?.reason||''} required><option value="">Choose reason</option>{['NO_SUITABLE_FACULTY','DECLINED','CAPACITY','AWAITING_ACTION','RELEVANCE_UNRESOLVED','OTHER'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="text-xs">Explanation<input name="reason" defaultValue={call.disposition?.explanation||''} className={`${field} block`} placeholder="Required for Other"/></label><HelpButton help="Save an auditable explanation for why this relevant opportunity was not taken up." className="nk-btn-secondary nk-btn-xs">Save reason</HelpButton></form>{error&&<p role="alert" className="text-red-700">{error}</p>}
  </div>
}

function ApplicationPanel({id,query,onClose,onSaved}:{id:string;query:string;onClose:()=>void;onSaved:()=>void}) {
  const {authFetch}=useAuth();const [data,setData]=useState<any>(null);const [error,setError]=useState('');const closeRef=useRef<HTMLButtonElement>(null)
  const load=useCallback(async()=>{const r=await authFetch(`/api/funding-dept/reports/applications/${encodeURIComponent(id)}?${query}`);const json=await r.json();if(!r.ok)throw Error(json.error);setData(json)},[authFetch,id,query])
  useEffect(()=>{load().catch(e=>setError(e.message))},[load])
  useEffect(()=>{const focused=document.activeElement as HTMLElement|null;const scroll=window.scrollY;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const panel=closeRef.current?.closest('[role="dialog"]');const nodes=panel?.querySelectorAll<HTMLElement>('button:not([disabled]), input, select, textarea, a[href], summary');if(nodes?.length){const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}};document.addEventListener('keydown',handler);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handler);focused?.focus({preventScroll:true});window.scrollTo(0,scroll)}},[onClose])
  const saved=()=>{load().catch(e=>setError(e.message));onSaved()}
  const a:App|undefined=data?.application
  const download=async(url:string,name:string)=>{try{const r=await authFetch(url);if(!r.ok)throw Error('Document unavailable or outside your access.');const blob=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=blob;link.download=name;link.click();URL.revokeObjectURL(blob)}catch(e){setError((e as Error).message)}}
  const verify=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();try{const reason=new FormData(e.currentTarget).get('reason');const r=await authFetch(`/api/funding-dept/actions?${query}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'verify',schoolId:a!.school_id,applicationId:id,reason})});if(!r.ok)throw Error((await r.json()).error);saved()}catch(e){setError((e as Error).message)}}
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/30"><section role="dialog" aria-modal="true" aria-labelledby="application-heading" className="h-full w-full max-w-4xl overflow-y-auto bg-white p-6 shadow-xl"><div className="flex justify-between gap-3"><h2 id="application-heading" className="text-xl font-semibold">Application details</h2><button ref={closeRef} title="Close this panel and return to the same report position and filters." className="nk-btn-secondary nk-btn-sm" onClick={onClose}>Close</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{!a?<p>Loading…</p>:<div className="space-y-6 mt-4">
    <div><h3 className="font-semibold">{a.title}</h3><p>{a.faculty?.name} · {label(a.stage)} · {label(a.workState)}</p><p className="nk-sub">Accountable: {data.accountableOfficer} · {a.independent?'Independent application':`Allocated by ${a.allocatedBy?.name||'Not recorded'} on ${date(a.created_at)}`}</p><p className="text-amber-700">{a.exceptions.join(' · ')}</p></div>
    <section><h3 className="font-semibold mb-2">Actions and named owners</h3>{a.actions.map(action=><div className="border-b py-3" key={action.id}><p>{action.is_next?'Next: ':''}{action.title} · {action.owner_name} · {label(action.waiting_with)} · {label(action.status)}</p><p className="nk-sub">Due {date(action.due_at)} · {action.blocker||'No blocker recorded'}</p><ActionEditor schoolId={a.school_id!} applicationId={id} people={data.people} existing={action} query={query} onSaved={saved}/></div>)}<ActionEditor schoolId={a.school_id!} applicationId={id} people={data.people} suggested={a.suggestedActionOwner} query={query} onSaved={saved}/></section>
    {a.assignment_id&&<section><h3 className="font-semibold mb-2">Record faculty follow-up or submission</h3><FollowUpPanel assignmentId={a.assignment_id} formOnly onLogged={saved}/></section>}
    <section><h3 className="font-semibold">Submission and funding</h3><p>{a.submitted?(a.verification?`Verified on ${date(a.verification.verified_at)} by ${data.people.find((p:Person)=>p.id===a.verification!.reviewer_user_id)?.name||a.verification.reviewer_user_id}`:'Recorded, not verified'):'Not submitted'}</p><p>Date: {date(a.submitted_at)} · Reference: {a.submission_reference||'Not recorded'}</p><p>Recorded by: {a.submissionRecorder?.name||'Not recorded'}</p>{a.submission_url&&/^https?:\/\//i.test(a.submission_url)&&<a href={a.submission_url} target="_blank" rel="noreferrer" className="text-cobalt-700 underline">Open submission portal record</a>}<p>{a.submission_notes}</p><p>{a.currency} requested: {a.requested_amount??'Not recorded'} · sanctioned: {a.sanctioned_amount??'Not recorded'}</p><p>Final decision: {['SANCTIONED','REJECTED'].includes(a.stage)?label(a.stage):'Not recorded'}</p>{a.submitted&&!a.verification&&<form onSubmit={verify} className="flex gap-2 mt-2"><input name="reason" required className={`${field} flex-1`} placeholder="Describe the reference, portal record or proof you reviewed"/><HelpButton help={a.evidenceAvailable?'Confirm that the saved reference, portal record or document proves submission.':'Upload or record a reference, portal link or submission document before verification.'} disabled={!a.evidenceAvailable} className="nk-btn-primary nk-btn-sm">Verify submission</HelpButton></form>}<p className="nk-sub">Notes alone are not evidence. Evidence corrections invalidate previous verification.</p></section>
    <section><h3 className="font-semibold">Proposal versions and uploaded evidence</h3>{data.proposal?.versions.map((v:any)=><p key={v.id}><button title="Download this saved proposal version." className="text-cobalt-700" onClick={()=>download(`/api/funding-dept/reports/applications/${encodeURIComponent(id)}/documents/${v.id}?kind=version&${query}`,v.file_name)}>Version {v.version_no}: {v.file_name}</button> · {v.review_status} · {v.review?.recommendation||'Review outcome not recorded'}</p>)}{[...(data.assignmentDocuments||[]).map((d:any)=>({...d,source:'assignment'})),...(data.proposal?.documents||[]).map((d:any)=>({...d,source:'proposal'}))].map((d:any)=><p key={d.id}><button title="Download this supporting or submission-evidence document." className="text-cobalt-700" onClick={()=>download(`/api/funding-dept/reports/applications/${encodeURIComponent(id)}/documents/${d.id}?kind=${d.source}&${query}`,d.file_name||'document')}>{d.file_name||d.title||d.kind}</button> · {d.kind}</p>)}</section>
    <section><h3 className="font-semibold">Complete follow-up history</h3>{a.contacts.length?a.contacts.map(c=><div className="border-b py-2" key={c.id}><p>{date(c.happened_at)} · {c.actor_name} · {label(c.kind)} · {label(c.target)}</p><p className="nk-sub whitespace-pre-wrap">{c.note}</p></div>):<p className="nk-sub">No contacts recorded.</p>}</section>
    <section><h3 className="font-semibold">Status, audit and ownership history</h3>{data.proposal?.events.map((e:any)=><p className="text-sm border-b py-2" key={e.id}>{date(e.created_at)} · {e.actor?.name||'Actor not recorded'} · {e.kind} {e.from_status?`${e.from_status} → ${e.to_status}`:''}</p>)}{data.events.map((e:any)=><details className="border-b py-2 text-sm" key={e.id}><summary>{date(e.occurred_at)} · {e.actor||'Actor not recorded'} · {label(e.entity_type)} / {label(e.kind)} {e.inferred?'(inferred baseline)':''}</summary><p>{e.reason}</p><pre className="whitespace-pre-wrap text-xs">{JSON.stringify({before:e.before_data,after:e.after_data},null,2)}</pre></details>)}</section>
  </div>}</section></div>
}
