'use client'

import { Fragment, useCallback, useEffect, useRef, useState } from 'react'
import { useAuth } from '@/lib/auth-context'
import type { ManagementReport } from '@/lib/fundingDept/managementService'

type Wire<T> = T extends Date ? string : T extends Array<infer U> ? Wire<U>[] : T extends object ? { [K in keyof T]: Wire<T[K]> } : T
type Report = Wire<ManagementReport>
type App = Report['applications'][number]
type Call = Report['members'][number]['schools'][number]['calls'][number]
type Action = Report['actions'][number]
type Person = { id:string; name:string | null }
type Payload = { snapshot?:string; members?:Report['members']; rows?:any[]; total?:number; totals:Report['totals']; quality:Report['quality']; options:Report['options']; activity:Report['activity']; asOf:string; windowLabel:string; lens:string; portfolio:string; membersMovement?:any[]; complete?:boolean; note?:string; definition?:string; urgentActions?:Action[]; unallocated?:Call[]; actions?:Action[] }
const views = [['member-funnel','Member → school → call'],['pending','Pending work'],['deadline-risk','Deadline risk'],['coverage','Faculty coverage'],['outcomes','Submissions & outcomes'],['performance','Member performance'],['weekly-review','Weekly review']]
const label = (s:string) => s.toLowerCase().replace(/_/g,' ').replace(/^./,c=>c.toUpperCase())
const date = (s?:string|null) => s ? new Date(s).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric'}) : 'Not recorded'
const field = 'rounded border border-nickel-300 bg-white px-2 py-1.5 text-sm'
const stages = ['AWAITING_FACULTY_RESPONSE','ACCEPTED_IN_HAND','PROPOSAL_DRAFTING','INTERNAL_REVIEW','CLEARED_AND_READY','SUBMITTED','UNDER_AGENCY_REVIEW','REVISION_REQUESTED','SANCTIONED','REJECTED','DECLINED','CANCELLED','LAPSED_NOT_APPLIED']

function useReport(path:string, revision=0) {
  const { authFetch }=useAuth();const [data,setData]=useState<Payload|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [loadedPath,setLoadedPath]=useState('')
  useEffect(()=>{let current=true;setLoading(true);setError('');authFetch(path).then(async r=>{const json=await r.json();if(!r.ok)throw Error(json.error||'Unable to load report');if(current){setData(json);setLoadedPath(path)}}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[path,revision,authFetch])
  return {data,error,loading,loadedPath}
}
function Pager({page,total=0,onChange}:{page:number;total?:number;onChange:(n:number)=>void}) {return <div className="flex items-center justify-end gap-3 p-3 text-sm"><span>{total} records · Page {page} of {Math.max(1,Math.ceil(total/20))}</span><button className="nk-btn-secondary nk-btn-xs" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</button><button className="nk-btn-secondary nk-btn-xs" disabled={page*20>=total} onClick={()=>onChange(page+1)}>Next</button></div>}
function Table({head,children}:{head:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-nickel-50"><tr>{head.map(h=><th key={h} className="px-3 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Cell({children}:{children:React.ReactNode}){return <td className="border-t border-nickel-100 px-3 py-3 align-top">{children}</td>}
function Ratio({value}:{value:{numerator:number;denominator:number;percent:number|null}}){return <span>{value.numerator}/{value.denominator} ({value.percent===null?'—':`${Math.round(value.percent)}%`})</span>}
function AppTable({apps,onOpen}:{apps:App[];onOpen:(id:string)=>void}) {return <Table head={['Faculty / application','Accountable / next owner','Stage / work state','Days waiting','Follow-up','Deadlines','Submission']}>
  {apps.map(a=><tr key={a.id}><Cell><button className="text-cobalt-700 text-left font-medium hover:underline" onClick={()=>onOpen(a.id)}>{a.faculty?.name || 'Faculty not recorded'}</button><p className="nk-sub">{a.title}</p><span className="nk-badge">{a.independent?'Independent application':'Formal allocation'}</span></Cell>
    <Cell>{(a as App & {accountableOfficer?:string}).accountableOfficer || 'See portfolio'}<p>{a.nextAction?.owner_name || 'Next owner not confirmed'}</p><p className="nk-sub">{a.nextAction?.title || 'Confirm a next action'}</p>{a.nextAction?.waiting_with==='AGENCY'&&<p className="nk-sub">Waiting externally; DSR follow-up owner above</p>}</Cell>
    <Cell>{label(a.stage)}<p className="nk-sub">{label(a.workState)}</p>{a.exceptions.map(e=><span className="nk-badge nk-badge-warn mr-1" key={e}>{label(e.replace(/-/g,'_'))}</span>)}</Cell>
    <Cell>{a.daysWaiting===null?'Not recorded':`${a.daysWaiting} days`}<p className="nk-sub">Since {date(a.stageEnteredAt)}</p></Cell>
    <Cell>{a.contactEvents} faculty contacts<p className="nk-sub">{a.lastContact?`Performed by ${a.lastContact.actor_name}`:'No external faculty contact'}</p></Cell>
    <Cell><p>Agency: {date(a.agency_deadline)}</p><p>Internal: {date(a.internal_deadline)}</p><p>Review: {date(a.review_deadline)}</p><p>Action: {date(a.nextAction?.due_at)}</p></Cell>
    <Cell>{a.submitted?(a.verification?'Verified':'Recorded · unverified'):'Not submitted'}<p className="nk-sub">{a.submitted?date(a.submitted_at):''}</p></Cell></tr>)}
    {!apps.length&&<tr><td colSpan={7} className="p-6 text-center nk-sub">No applications match these filters.</td></tr>}
  </Table>}

export default function ManagementWorkspace({initialWindow='reporting'}:{initialWindow?:string}) {
  const {authFetch}=useAuth();const [view,setView]=useState('member-funnel');const [filters,setFilters]=useState<Record<string,string>>({window:initialWindow,mode:'pending'});const [page,setPage]=useState(1);const [expanded,setExpanded]=useState<Record<string,boolean>>({});const [detail,setDetail]=useState<string|null>(null);const [revision,setRevision]=useState(0);const [exportError,setExportError]=useState('')
  const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const base=query.toString();query.set('page',String(page))
  const snapshotCache=useRef(new Map<string,string>());const identity=`${view}?${base}@${revision}`;const cached=snapshotCache.current.get(identity);if(cached)query.set('snapshot',cached)
  const reportUrl=`/api/funding-dept/reports/${view}?${query}`
  const {data,error,loading,loadedPath}=useReport(reportUrl,revision)
  if(data?.snapshot && loadedPath===reportUrl)snapshotCache.current.set(identity,data.snapshot)
  const detailQuery=`${base}&snapshot=${data?.snapshot||''}`
  const catalog=useRef<Payload['options']|null>(null)
  if(data && (!catalog.current || (!filters.memberId&&!filters.schoolId&&!filters.callId)))catalog.current=data.options
  const update=(key:string,value:string)=>{setFilters(f=>({...f,[key]:value}));setPage(1)}
  const toggle=(id:string)=>setExpanded(e=>({...e,[id]:!e[id]}))
  const refresh=()=>setRevision(r=>r+1)
  const closeDetail=useCallback(()=>setDetail(null),[])
  const select=(key:string,title:string,options:Array<[string,string]>)=><label className="flex flex-col gap-1 text-xs">{title}<select className={field} value={filters[key]||''} onChange={e=>update(key,e.target.value)}><option value="">All</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
  const exportReport=async(format:string)=>{setExportError('');try{const response=await authFetch(`/api/funding-dept/reports/${view}?${detailQuery}&format=${format}`);if(!response.ok)throw Error((await response.json()).error);const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`dsr-${view}.${format}`;a.click();URL.revokeObjectURL(url)}catch(e){setExportError((e as Error).message)}}
  return <div className="space-y-5">
    <nav className="flex flex-wrap gap-2 border-b border-nickel-200 pb-3" aria-label="Management reports">{views.map(([id,name])=><button key={id} className={view===id?'nk-btn-primary nk-btn-sm':'nk-btn-secondary nk-btn-sm'} onClick={()=>{setView(id);setPage(1)}}>{name}</button>)}</nav>
    <div className="nk-panel p-4 space-y-3"><div className="flex flex-wrap items-end gap-3">
      <label className="flex flex-col gap-1 text-xs">Report view<select className={field} value={filters.mode} onChange={e=>update('mode',e.target.value)}><option value="pending">Pending now · all ages</option><option value="cohort">Opportunity cohort</option><option value="activity">Period activity</option></select></label>
      <label className="flex flex-col gap-1 text-xs">Period<select className={field} value={filters.window} onChange={e=>update('window',e.target.value)}><option value="reporting">Department reporting period</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="custom">Custom dates</option></select></label>
      {filters.window==='custom'&&<><label className="text-xs">From <input aria-label="From date" type="date" className={field} value={filters.from||''} onChange={e=>update('from',e.target.value)}/></label><label className="text-xs">To <input aria-label="To date" type="date" className={field} value={filters.to||''} onChange={e=>update('to',e.target.value)}/></label></>}
      {data?.lens==='department'&&select('memberId','Primary member',(catalog.current?.members||[]).map(m=>[m.id,m.name]))}
      {select('schoolId','School',(catalog.current?.schools||[]).map(s=>[s.id,s.name]))}
      <label className="flex flex-col gap-1 text-xs">Call filter<input placeholder="Call title or identifier" className={field} value={filters.callSearch||''} onChange={e=>update('callSearch',e.target.value)}/></label>
      {data?.lens==='member'&&<label className="flex flex-col gap-1 text-xs">Portfolio<select className={field} value={filters.portfolio||'primary'} onChange={e=>{update('portfolio',e.target.value);catalog.current=null}}><option value="primary">My primary accountability</option><option value="deputy">My deputy operational view</option></select></label>}
    </div><details><summary className="cursor-pointer text-sm">Status, quality and exception filters</summary><div className="flex flex-wrap gap-3 pt-3">
      {select('workState','Work state',[['PENDING','Pending'],['SUBMITTED','Submitted'],['CLOSED_WITHOUT_SUBMISSION','Closed without submission']])}
      {select('stage','Detailed stage',stages.map(s=>[s,label(s)]))}
      {select('relevance','Relevance',[['confirmed','Confirmed'],['unclassified','Unclassified'],['unmapped','School unmapped'],['dismissed','Manually not relevant'],['ad-hoc','Ad-hoc']])}
      {select('exception','Exceptions',[['overdue','Overdue'],['no-follow-up','No faculty follow-up'],['missing-submission-proof','Missing submission evidence'],['missing-deadline','Missing agency deadline']])}
      {select('horizon','Deadline window',[['7','Within 7 days / overdue'],['14','Within 14 days / overdue'],['30','Within 30 days / overdue']])}
      {select('waitingWith','Waiting with',['FACULTY','DSR','REVIEWER','APPROVER','AGENCY'].map(s=>[s,label(s)]))}
    </div></details><p className="nk-sub">{filters.mode==='pending'?'Outstanding applications and open unallocated opportunities, including older work.':filters.mode==='cohort'?'Opportunities first evidenced in the selected period, followed to their latest outcome. Unknown first-seen dates are excluded, not guessed.':'Applications with allocations, external faculty contacts, submissions or action completions in the selected period. Activity totals below count events within that period.'}</p></div>
    <div className="flex justify-between gap-3 text-xs"><span>{data?`${data.windowLabel} · India time · Report as of ${new Date(data.asOf).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}`:''}</span><div className="flex gap-2"><button className="nk-btn-secondary nk-btn-xs" onClick={refresh}>Refresh</button><button className="nk-btn-secondary nk-btn-xs" onClick={()=>exportReport('csv')}>Export all CSV</button><button className="nk-btn-secondary nk-btn-xs" onClick={()=>exportReport('xlsx')}>Export all XLSX</button></div></div>
    {(error||exportError)&&<p role="alert" className="text-red-700">{error||exportError}</p>}
    {loading&&<p role="status" className="nk-sub">Loading report…</p>}
    {data&&!error&&<>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Call–school opportunities',data.totals.callSchoolOpportunities],['Distinct confirmed calls',data.totals.distinctCalls],['Formal allocations',data.totals.allocated],['Independent applications',data.totals.independent],['Pending before submission',data.totals.pending],['Recorded submissions',data.totals.submitted],['Verified submissions',data.totals.verified],['Needs attention',data.totals.needsAttention]].map(([title,value])=><div className="nk-panel p-3" key={title}><p className="nk-sub">{title}</p><p className="text-2xl font-semibold">{value}</p></div>)}</div>
      <p className="nk-sub">Submission split: {data.totals.allocatedSubmissions} allocated + {data.totals.independentSubmissions} independent. Period activity: {data.activity.allocations} allocations · {data.activity.independent} independent applications · {data.activity.contacts} faculty contact events · {data.activity.submissions} submissions.</p>
      <div className="rounded border border-amber-200 bg-amber-50 p-3 text-xs">Data quality: {data.totals.unclassified} unclassified call–school records · {data.totals.unmapped} unmapped · {data.quality.unknownStageDates} application stage-entry dates not recorded. {!data.quality.matchingComplete&&'Faculty matching is incomplete: recorded matches are not a complete count of all suitable faculty.'} Historical matches labelled inferred: {data.quality.inferredMatches}. {data.portfolio==='deputy'&&'Deputy operational view only; do not add these totals to primary accountability.'}</div>
      {view==='member-funnel'&&<section className="nk-panel"><Table head={['Primary DSR member','Schools','Relevant opportunities','Faculty matches','Allocated / independent','Followed up','Submitted / verified','Needs attention']}>
        {(data.members||[]).map(m=><Fragment key={m.id}><tr><Cell><button className="text-cobalt-700 font-medium" aria-expanded={!!expanded[m.id]} onClick={()=>toggle(m.id)}>{expanded[m.id]?'−':'+'} {m.name}</button></Cell><Cell>{m.childCount}</Cell><Cell>{m.totals.callSchoolOpportunities}</Cell><Cell>{m.totals.facultyMatches}</Cell><Cell>{m.totals.allocated} / {m.totals.independent}</Cell><Cell>{m.totals.followedUp} allocations</Cell><Cell>{m.totals.submitted} / {m.totals.verified}</Cell><Cell>{m.totals.needsAttention}</Cell></tr>
          {expanded[m.id]&&<tr><td colSpan={8} className="p-4 bg-nickel-50"><Table head={['School','Relevant calls','Matches','Allocated / independent','Pending','Followed up','Submitted','Overdue']}>
            {m.schools.map(s=><Fragment key={s.id}><tr><Cell><button className="text-cobalt-700" aria-expanded={!!expanded[s.id]} onClick={()=>toggle(s.id)}>{expanded[s.id]?'−':'+'} {s.name}</button>{s.isUnmapped&&<p className="text-amber-700">School mapping incomplete</p>}</Cell>{['relevant','matches','allocated','pending','followedUp','submitted','overdue'].map(key=><Cell key={key}>{(s as any).totals[key]}{key==='allocated'?` / ${(s as any).totals.independent}`:''}</Cell>)}</tr>
              {expanded[s.id]&&<tr><td colSpan={8} className="p-3"><SchoolCalls schoolId={s.id} memberId={m.id} query={detailQuery} revision={revision} onOpen={setDetail} refresh={refresh}/></td></tr>}
            </Fragment>)}
          </Table></td></tr>}
        </Fragment>)}
      </Table>{!data.members?.length&&<p className="p-5 nk-sub">No accessible school portfolios match these filters.</p>}</section>}
      {['pending','deadline-risk','outcomes'].includes(view)&&<section className="nk-panel">
        {view==='pending'?['FACULTY','DSR','REVIEWER','APPROVER','AGENCY','UNASSIGNED'].map(group=>{const apps=(data.rows||[]).filter(a=>(a.nextAction?.waiting_with||'UNASSIGNED')===group);return apps.length?<div key={group}><h2 className="p-3 font-medium">Waiting with {label(group)}</h2><AppTable apps={apps} onOpen={setDetail}/></div>:null}):<AppTable apps={data.rows||[]} onOpen={setDetail}/>}
        <Pager page={page} total={data.total} onChange={setPage}/>
        {!!data.unallocated?.length&&<div className="p-3"><h2 className="font-medium">Relevant opportunities with no formal allocation</h2>{data.unallocated.map(c=><details key={`${c.schoolId}:${c.id}`} className="border-t py-3"><summary className="cursor-pointer">{c.title} · {c.matchedFaculty} recorded matches · agency {date(c.deadline)}</summary><OpportunityActions call={c} people={data.options.people} query={base} refresh={refresh}/></details>)}</div>}
      </section>}
      {view==='coverage'&&<section className="nk-panel"><Table head={['Faculty','Suitable opportunities','Approached','Never approached','Allocations','Active applications','Submitted']}>
        {(data.rows||[]).map(p=><tr key={p.id}>{[p.name,p.suitableOpportunities,p.approached,p.neverApproached,p.allocations,p.active,p.submitted].map((v,i)=><Cell key={i}>{v}</Cell>)}</tr>)}
      </Table><p className="p-3 nk-sub">Recorded faculty matches only. Multiple active applications indicate workload, not an overload judgement.</p><Pager page={page} total={data.total} onChange={setPage}/></section>}
      {view==='performance'&&<div className="space-y-3">{(data.rows||[]).map(p=><section className="nk-panel p-4" key={p.id}><h2 className="font-semibold">{p.name}</h2><div className="grid gap-4 md:grid-cols-3 mt-3"><div><h3 className="font-medium">Workload</h3><p>{p.workload.callSchoolOpportunities} opportunities · {p.workload.outstanding} outstanding applications</p><p>{p.inheritedBacklog ?? 'Not recorded'} inherited backlog</p></div><div><h3 className="font-medium">Execution</h3><p>Faculty contact coverage: <Ratio value={p.facultyContactCoverage}/></p><p>Timely completed actions: <Ratio value={p.timelyActions}/></p><p>Allocation median: {p.medianAllocationDays?.toFixed(1)??'—'} days ({p.allocationSample} completed allocations)</p><p>First faculty contact after allocation: {p.medianFirstContactDays?.toFixed(1)??'—'} days ({p.firstContactSample} cases; {p.awaitingContact} still awaiting)</p><p>{p.performedContacts} contact events performed by this member</p></div><div><h3 className="font-medium">Results</h3><p>Cohort submission conversion: <Ratio value={p.submissionConversion}/></p><p>{p.independentSubmissions} independent submissions (separate)</p><p>Funding success: <Ratio value={p.fundingSuccess}/> · {p.undecided} undecided</p><p>Submissions by submission date: {p.periodSubmissions} vs {p.previousPeriodSubmissions} previous equal-length period</p>{Object.entries(p.money as Record<string,{requested:number;sanctioned:number}>).map(([currency,m])=><p key={currency}>{currency}: requested {m.requested.toLocaleString()} · sanctioned {m.sanctioned.toLocaleString()}</p>)}</div></div></section>)}</div>}
      {view==='weekly-review'&&<section className="nk-panel p-4"><h2 className="font-semibold">Backlog movement</h2><p className="nk-sub">{data.definition}</p>{!data.complete&&<p className="text-amber-700 my-3">{data.note}</p>}<Table head={['Member','Opening','New','Reopened','Transferred in','Resolved','Transferred out','Closing','Reconciled']}>
        {(data.members||[]).map((m:any)=><tr key={m.id}>{[m.name,m.opening,m.newWork,m.reopened,m.transfersIn,m.resolved,m.transfersOut,m.closing,m.reconciled===null?'Incomplete':m.reconciled?'Yes':'Check required'].map((v,i)=><Cell key={i}>{v}</Cell>)}</tr>)}
      </Table><h3 className="font-medium mt-4">Urgent decisions and blockers</h3>{data.urgentActions?.map(a=><p key={a.id} className="mt-2"><button className="text-cobalt-700" disabled={!a.application_id} onClick={()=>setDetail(a.application_id)}>{a.title}</button> · {a.owner_name} · {date(a.due_at)} · {a.blocker||'Overdue action'}</p>)}</section>}
    </>}
    {detail&&<ApplicationPanel id={detail} query={base} onClose={closeDetail} onSaved={refresh}/>}
  </div>
}

function SchoolCalls({schoolId,memberId,query,revision,onOpen,refresh}:{schoolId:string;memberId:string;query:string;revision:number;onOpen:(id:string)=>void;refresh:()=>void}) {
  const [page,setPage]=useState(1);const [open,setOpen]=useState<Record<string,boolean>>({});const q=new URLSearchParams(query);q.set('drillSchoolId',schoolId);if(q.get('portfolio')!=='deputy')q.set('drillMemberId',memberId);q.set('level','calls');q.set('page',String(page))
  const {data,error,loading}=useReport(`/api/funding-dept/reports/member-funnel?${q}`,revision)
  useEffect(()=>setPage(1),[query])
  return <div className="bg-white rounded border border-nickel-200">{error&&<p role="alert">{error}</p>}{loading&&<p className="p-3 nk-sub">Loading calls…</p>}{data?.rows?.map((c:Call)=><div key={c.id} className="border-b p-3"><button className="text-cobalt-700 text-left font-medium" aria-expanded={!!open[c.id]} onClick={()=>setOpen(o=>({...o,[c.id]:!o[c.id]}))}>{open[c.id]?'−':'+'} {c.title}</button><p className="nk-sub">{c.agency} · Agency deadline {date(c.deadline)} · {label(c.quality)} · {c.reason||'Reason not recorded'}</p><p className="text-sm mt-2">{c.matchedFaculty} saved matches ({label(c.matchCompleteness)}) · {c.approached} approached · {c.allocated} allocations + {c.independent} independent · {c.pending} pending · {c.submitted} submitted · {c.overdue} overdue</p><p className="nk-sub">Last action: {c.lastAction?`${date(c.lastAction.at)} · Performed by ${c.lastAction.by}`:'Not recorded'}</p>{c.unallocated&&<p className="text-amber-700 text-sm">Relevant opportunity with nobody formally allocated.</p>}
    <p className="text-sm">{c.followedUp} followed up · {c.verified} verified · {c.declined} declined · {c.lapsed} lapsed</p>
    {open[c.id]&&<div className="mt-3 space-y-3"><CallApplications query={q.toString()} callId={c.id} revision={revision} onOpen={onOpen}/><OpportunityActions call={c} people={data.options.people} query={query} refresh={refresh}/><MatchRows query={q.toString()} callId={c.id} revision={revision}/></div>}
  </div>)}{data&&!data.rows?.length&&<p className="p-4 nk-sub">No calls match this view. Unknown first-seen dates are excluded from cohorts.</p>}<Pager page={page} total={data?.total} onChange={setPage}/></div>
}
function CallApplications({query,callId,revision,onOpen}:{query:string;callId:string;revision:number;onOpen:(id:string)=>void}) {const [page,setPage]=useState(1);const q=new URLSearchParams(query);q.set('drillCallId',callId);q.set('level','applications');q.set('page',String(page));const {data,error}=useReport(`/api/funding-dept/reports/member-funnel?${q}`,revision);return <>{error&&<p role="alert">{error}</p>}<AppTable apps={data?.rows||[]} onOpen={onOpen}/><Pager page={page} total={data?.total} onChange={setPage}/></>}
function MatchRows({query,callId,revision}:{query:string;callId:string;revision:number}) {const [show,setShow]=useState(false);return <details onToggle={e=>setShow(e.currentTarget.open)}><summary className="cursor-pointer text-sm">Saved faculty matching evidence</summary>{show&&<MatchPage query={query} callId={callId} revision={revision}/>}</details>}
function MatchPage({query,callId,revision}:{query:string;callId:string;revision:number}) {const [page,setPage]=useState(1);const q=new URLSearchParams(query);q.set('drillCallId',callId);q.set('level','matches');q.set('page',String(page));const {data,error}=useReport(`/api/funding-dept/reports/member-funnel?${q}`,revision);return <>{error&&<p role="alert">{error}</p>}<Table head={['Faculty','Score','Reason','Source / version','First seen']}>
  {data?.rows?.map(m=><tr key={m.id}><Cell>{m.faculty?.name||m.user_id}</Cell><Cell>{m.match_score??'Unknown'}</Cell><Cell>{m.match_reason||'Not recorded'}</Cell><Cell>{m.source} / {m.source_version||'Not recorded'} {m.inferred?'· inferred':''}</Cell><Cell>{date(m.first_seen_at)}</Cell></tr>)}
  </Table><Pager page={page} total={data?.total} onChange={setPage}/></>}

function ActionEditor({schoolId,applicationId,callId,people,query,existing,suggested,onSaved}:{schoolId:string;applicationId?:string|null;callId?:string|null;people:Person[];query:string;existing?:Action;suggested?:Person|null;onSaved:()=>void}) {
  const {authFetch}=useAuth();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [show,setShow]=useState(false)
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const data=new FormData(form);try{const due=data.get('dueAt') as string;const response=await authFetch(`/api/funding-dept/actions?${query}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({schoolId,applicationId,callId,id:existing?.id,version:existing?.version,title:data.get('title'),ownerUserId:data.get('owner'),waitingWith:data.get('waiting'),dueAt:due?new Date(`${due}:00+05:30`).toISOString():null,deadlineType:data.get('deadlineType'),blocker:data.get('blocker')||null,reason:data.get('reason')||undefined,isNext:data.get('next')==='on',status:data.get('status')||'OPEN'})});const json=await response.json();if(!response.ok)throw Error(json.error);setShow(false);onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div><button className="nk-btn-secondary nk-btn-xs" onClick={()=>setShow(s=>!s)}>{existing?'Edit / complete / reopen':'Add action'}</button>{show&&<form onSubmit={save} className="grid gap-3 rounded border p-3 mt-2 sm:grid-cols-2">
    <label className="text-xs">Action<input name="title" required maxLength={1000} defaultValue={existing?.title} className={`${field} block w-full`}/></label>
    <label className="text-xs">Confirmed named owner<select name="owner" required defaultValue={existing?.owner_user_id||''} className={`${field} block w-full`}><option value="">Select and confirm a person</option>{people.map(p=><option key={p.id} value={p.id}>{p.name||p.id}</option>)}</select>{suggested&&<span>Suggested: {suggested.name}. Please confirm explicitly.</span>}</label>
    <label className="text-xs">Waiting with<select name="waiting" required defaultValue={existing?.waiting_with||''} className={`${field} block w-full`}><option value="">Choose category</option>{['FACULTY','DSR','REVIEWER','APPROVER','AGENCY'].map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="text-xs">Action due (India time)<input name="dueAt" type="datetime-local" defaultValue={existing?.due_at?new Date(new Date(existing.due_at).getTime()+330*60000).toISOString().slice(0,16):''} className={`${field} block w-full`}/></label>
    <label className="text-xs">Deadline type<select name="deadlineType" defaultValue={existing?.deadline_type||'ACTION'} className={`${field} block w-full`}>{['ACTION','AGENCY','INTERNAL_REVIEW','REVISION'].map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="text-xs">Status<select name="status" defaultValue={existing?.status||'OPEN'} className={`${field} block w-full`}><option value="OPEN">Open / reopen</option><option value="DONE">Completed</option></select></label>
    <label className="text-xs">Blocker<input name="blocker" defaultValue={existing?.blocker||''} className={`${field} block w-full`}/></label>
    <label className="text-xs">Reason (required for reassignment or extension)<input name="reason" className={`${field} block w-full`}/></label>
    <label className="text-sm"><input name="next" type="checkbox" defaultChecked={existing?.is_next??true}/> Designate as next action</label>
    <div><button className="nk-btn-primary nk-btn-sm" disabled={busy}>{busy?'Saving…':'Save action'}</button><button type="button" className="nk-btn-secondary nk-btn-sm ml-2" onClick={()=>setShow(false)}>Cancel</button></div>{error&&<p role="alert" className="text-red-700 sm:col-span-2">{error}</p>}
  </form>}</div>
}
function OpportunityActions({call,people,query,refresh}:{call:Call;people:Person[];query:string;refresh:()=>void}) {
  const {authFetch}=useAuth();const [error,setError]=useState('');if(call.id.startsWith('adhoc:'))return null
  async function disposition(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setError('');try{const response=await authFetch(`/api/funding-dept/actions?${query}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'disposition',schoolId:call.schoolId,callId:call.id,disposition:data.get('disposition'),reason:data.get('reason')||undefined})});if(!response.ok)throw Error((await response.json()).error);refresh()}catch(e){setError((e as Error).message)}}
  return <div className="space-y-3"><h4 className="text-sm font-medium">Opportunity actions</h4>{call.actions.map(a=><div key={a.id} className="text-sm">{a.is_next?'Next: ':''}{a.title} · {a.owner_name} · {label(a.status)} · {date(a.due_at)}<ActionEditor schoolId={call.schoolId} callId={call.id} people={people} query={query} existing={a} onSaved={refresh}/></div>)}<ActionEditor schoolId={call.schoolId} callId={call.id} people={people} suggested={call.suggestedActionOwner} query={query} onSaved={refresh}/>
    <form onSubmit={disposition} className="flex flex-wrap items-end gap-2"><label className="text-xs">No uptake reason<select name="disposition" className={`${field} block`} defaultValue={call.disposition?.reason||''} required><option value="">Choose reason</option>{['NO_SUITABLE_FACULTY','DECLINED','CAPACITY','AWAITING_ACTION','RELEVANCE_UNRESOLVED','OTHER'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="text-xs">Explanation<input name="reason" defaultValue={call.disposition?.explanation||''} className={`${field} block`} placeholder="Required for Other"/></label><button className="nk-btn-secondary nk-btn-xs">Save reason</button></form>{error&&<p role="alert" className="text-red-700">{error}</p>}
  </div>
}

function ApplicationPanel({id,query,onClose,onSaved}:{id:string;query:string;onClose:()=>void;onSaved:()=>void}) {
  const {authFetch}=useAuth();const [data,setData]=useState<any>(null);const [error,setError]=useState('');const closeRef=useRef<HTMLButtonElement>(null)
  const load=useCallback(async()=>{const r=await authFetch(`/api/funding-dept/reports/applications/${encodeURIComponent(id)}?${query}`);const json=await r.json();if(!r.ok)throw Error(json.error);setData(json)},[authFetch,id,query])
  useEffect(()=>{load().catch(e=>setError(e.message))},[load])
  useEffect(()=>{const focused=document.activeElement as HTMLElement|null;const scroll=window.scrollY;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const panel=closeRef.current?.closest('[role="dialog"]');const nodes=panel?.querySelectorAll<HTMLElement>('button:not([disabled]), input, select, textarea, a[href], summary');if(nodes?.length){const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}};document.addEventListener('keydown',handler);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handler);focused?.focus({preventScroll:true});window.scrollTo(0,scroll)}},[onClose])
  const saved=()=>{load().catch(e=>setError(e.message));onSaved()}
  const a:App|undefined=data?.application
  const download=async(url:string,name:string)=>{try{const r=await authFetch(url);if(!r.ok)throw Error('Document unavailable or outside your access.');const blob=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=blob;link.download=name;link.click();URL.revokeObjectURL(blob)}catch(e){setError((e as Error).message)}}
  const verify=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();try{const reason=new FormData(e.currentTarget).get('reason');const r=await authFetch(`/api/funding-dept/actions?${query}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'verify',schoolId:a!.school_id,applicationId:id,reason})});if(!r.ok)throw Error((await r.json()).error);saved()}catch(e){setError((e as Error).message)}}
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/30"><section role="dialog" aria-modal="true" aria-labelledby="application-heading" className="h-full w-full max-w-4xl overflow-y-auto bg-white p-6 shadow-xl"><div className="flex justify-between gap-3"><h2 id="application-heading" className="text-xl font-semibold">Application details</h2><button ref={closeRef} className="nk-btn-secondary nk-btn-sm" onClick={onClose}>Close</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{!a?<p>Loading…</p>:<div className="space-y-6 mt-4">
    <div><h3 className="font-semibold">{a.title}</h3><p>{a.faculty?.name} · {label(a.stage)} · {label(a.workState)}</p><p className="nk-sub">Accountable: {data.accountableOfficer} · {a.independent?'Independent application':`Allocated by ${a.allocatedBy?.name||'Not recorded'} on ${date(a.created_at)}`}</p><p className="text-amber-700">{a.exceptions.join(' · ')}</p></div>
    <section><h3 className="font-semibold mb-2">Actions and named owners</h3>{a.actions.map(action=><div className="border-b py-3" key={action.id}><p>{action.is_next?'Next: ':''}{action.title} · {action.owner_name} · {label(action.waiting_with)} · {label(action.status)}</p><p className="nk-sub">Due {date(action.due_at)} · {action.blocker||'No blocker recorded'}</p><ActionEditor schoolId={a.school_id!} applicationId={id} people={data.people} existing={action} query={query} onSaved={saved}/></div>)}<ActionEditor schoolId={a.school_id!} applicationId={id} people={data.people} suggested={a.suggestedActionOwner} query={query} onSaved={saved}/></section>
    <section><h3 className="font-semibold">Submission and funding</h3><p>{a.submitted?(a.verification?`Verified on ${date(a.verification.verified_at)} by ${data.people.find((p:Person)=>p.id===a.verification!.reviewer_user_id)?.name||a.verification.reviewer_user_id}`:'Recorded, not verified'):'Not submitted'}</p><p>Date: {date(a.submitted_at)} · Reference: {a.submission_reference||'Not recorded'}</p><p>Recorded by: {a.submissionRecorder?.name||'Not recorded'}</p>{a.submission_url&&/^https?:\/\//i.test(a.submission_url)&&<a href={a.submission_url} target="_blank" rel="noreferrer" className="text-cobalt-700 underline">Open submission portal record</a>}<p>{a.submission_notes}</p><p>{a.currency} requested: {a.requested_amount??'Not recorded'} · sanctioned: {a.sanctioned_amount??'Not recorded'}</p><p>Final decision: {['SANCTIONED','REJECTED'].includes(a.stage)?label(a.stage):'Not recorded'}</p>{a.submitted&&!a.verification&&<form onSubmit={verify} className="flex gap-2 mt-2"><input name="reason" required className={`${field} flex-1`} placeholder="Describe the reference, portal record or proof you reviewed"/><button disabled={!a.evidenceAvailable} className="nk-btn-primary nk-btn-sm">Verify submission</button></form>}<p className="nk-sub">Notes alone are not evidence. Evidence corrections invalidate previous verification.</p></section>
    <section><h3 className="font-semibold">Proposal versions and uploaded evidence</h3>{data.proposal?.versions.map((v:any)=><p key={v.id}><button className="text-cobalt-700" onClick={()=>download(`/api/funding-dept/reports/applications/${encodeURIComponent(id)}/documents/${v.id}?kind=version&${query}`,v.file_name)}>Version {v.version_no}: {v.file_name}</button> · {v.review_status} · {v.review?.recommendation||'Review outcome not recorded'}</p>)}{[...(data.assignmentDocuments||[]).map((d:any)=>({...d,source:'assignment'})),...(data.proposal?.documents||[]).map((d:any)=>({...d,source:'proposal'}))].map((d:any)=><p key={d.id}><button className="text-cobalt-700" onClick={()=>download(`/api/funding-dept/reports/applications/${encodeURIComponent(id)}/documents/${d.id}?kind=${d.source}&${query}`,d.file_name||'document')}>{d.file_name||d.title||d.kind}</button> · {d.kind}</p>)}</section>
    <section><h3 className="font-semibold">Complete follow-up history</h3>{a.contacts.length?a.contacts.map(c=><div className="border-b py-2" key={c.id}><p>{date(c.happened_at)} · {c.actor_name} · {label(c.kind)} · {label(c.target)}</p><p className="nk-sub whitespace-pre-wrap">{c.note}</p></div>):<p className="nk-sub">No contacts recorded.</p>}</section>
    <section><h3 className="font-semibold">Status, audit and ownership history</h3>{data.proposal?.events.map((e:any)=><p className="text-sm border-b py-2" key={e.id}>{date(e.created_at)} · {e.actor?.name||'Actor not recorded'} · {e.kind} {e.from_status?`${e.from_status} → ${e.to_status}`:''}</p>)}{data.events.map((e:any)=><details className="border-b py-2 text-sm" key={e.id}><summary>{date(e.occurred_at)} · {e.actor||'Actor not recorded'} · {label(e.entity_type)} / {label(e.kind)} {e.inferred?'(inferred baseline)':''}</summary><p>{e.reason}</p><pre className="whitespace-pre-wrap text-xs">{JSON.stringify({before:e.before_data,after:e.after_data},null,2)}</pre></details>)}</section>
  </div>}</section></div>
}
