import { Prisma } from '@prisma/client';
import prisma from '../prisma';
import type { RecommendationAccessScope } from '../recommendations/types';
import { sanitizeExternalUrl, sanitizeExternalUrls } from '../urlSafety';
import { EmbeddingService } from './embeddingService';
import { recommendationSearchService } from './recommendationSearchService';
import { resultRankingService } from './resultRankingService';

// Define the FundingCall type since it's not generated by Prisma yet
export interface FundingCall {
  id: string;
  countryAvailability: string[];
  eligibleApplicantCountries: string[];
  applicantTypes: string[];
  grantTypes: string[];
  agencyName: string;
  schemeTitle: string;
  description: string;
  deadline: Date | null;
  fundingAmount: string | null;
  eligibility: string | null;
  researchAreas: string[];
  urls: string[];
  contactInfo: string | null;
  createdAt: Date;
  updatedAt: Date;
  // Metadata fields
  source?: string | null;
  uploadedBy?: string | null;
  expirationDate?: Date | null;
  isActive?: boolean;
  version?: number;
  previousVersionId?: string | null;
  metadata?: Record<string, any> | null;
  status?: string;
  // New fields for URL and attachment
  callUrl?: string | null;
  attachmentFile?: string | null;
}

const embeddingService = new EmbeddingService();

interface SearchFilters {
  applicantTypes?: string[];
  grantTypes?: string[];
  countries?: string[];
  limit?: number;
  includeExpired?: boolean;
  access?: RecommendationAccessScope;
}

interface SearchResult {
  results: FundingCall[];
  similarity?: number[];
  error?: string;
}

function buildPublicationWhereClause(filters: SearchFilters): string {
  let whereConditions = ` AND catalog_status = 'PUBLISHED' AND COALESCE(is_active, true) = true`;

  if (!filters.includeExpired) {
    whereConditions += ` AND (
      COALESCE(is_rolling, false) = true OR
      COALESCE(close_date, expiration_date) IS NULL OR
      COALESCE(close_date, expiration_date) >= CURRENT_DATE
    )`;
  }

  return whereConditions;
}

/**
 * Service for managing funding calls and performing vector-based searches
 */
export class FundingCallsService {
  /**
   * Create a new funding call with vector embeddings
   */
  async createFundingCall(data: Omit<FundingCall, 'id' | 'createdAt' | 'updatedAt'>): Promise<FundingCall> {
    try {
      // Use raw SQL to create the funding call since Prisma doesn't fully support the model yet
      const result = await prisma.$executeRaw`
        INSERT INTO funding_calls (
          eligible_countries,
          host_countries,
          institution_types,
          funding_kinds,
          agency_name,
          scheme_title,
          description,
          close_date,
          eligibility_text,
          disciplines,
          official_urls,
          contact_info,
          source_url
        ) VALUES (
          ${data.eligibleApplicantCountries}::text[],
          ${data.countryAvailability}::text[],
          ${data.applicantTypes}::text[],
          ${data.grantTypes}::text[],
          ${data.agencyName},
          ${data.schemeTitle},
          ${data.description},
          ${data.deadline},
          ${data.eligibility},
          ${data.researchAreas}::text[],
          ${data.urls}::text[],
          ${data.contactInfo},
          ${data.callUrl}
        )
        RETURNING id
      `;
      
      const id = (result as any)[0]?.id;
      if (!id) throw new Error("Failed to create funding call");
      
      // Generate embedding for the funding call and update directly in the database
      await this.updateEmbedding(id);
      
      // Retrieve the full record
      const fundingCall = await this.getFundingCallById(id);
      if (!fundingCall) throw new Error("Failed to retrieve created funding call");
      
      return fundingCall;
    } catch (error) {
      console.error('Error creating funding call:', error);
      throw error;
    }
  }
  
  /**
   * Get a funding call by ID
   */
  async getFundingCallById(id: string): Promise<FundingCall | null> {
    try {
      const result = await prisma.$queryRaw`
        SELECT
          id, 
          scheme_title as "schemeTitle",
          agency_name as "agencyName",
          description,
          host_countries as "countryAvailability",
          eligible_countries as "eligibleApplicantCountries",
          institution_types as "applicantTypes",
          funding_kinds as "grantTypes",
          close_date as deadline,
          CASE
            WHEN amount_min IS NULL AND amount_max IS NULL THEN NULL
            ELSE trim(concat(COALESCE(currency, ''), ' ', COALESCE(amount_min::text, ''), CASE WHEN amount_max IS NOT NULL THEN concat(' - ', amount_max::text) ELSE '' END))
          END as "fundingAmount",
          eligibility_text as eligibility,
          disciplines as "researchAreas",
          official_urls as urls,
          contact_info as "contactInfo",
          created_at as "createdAt",
          updated_at as "updatedAt",
          catalog_status as status,
          is_active as "isActive",
          source_url as "callUrl",
          NULL::text as "attachmentFile"
        FROM funding_calls
        WHERE id = ${id}
      `;
      
      const calls = result as FundingCall[];
      if (calls.length === 0) {
        return null;
      }

      return {
        ...calls[0],
        urls: sanitizeExternalUrls(calls[0].urls),
        callUrl: sanitizeExternalUrl(calls[0].callUrl),
      };
    } catch (error) {
      console.error(`Error retrieving funding call ${id}:`, error);
      return null;
    }
  }
  
  /**
   * Generate and update the embedding for a funding call
   */
  async updateEmbedding(id: string): Promise<void> {
    try {
      const fundingCall = await this.getFundingCallById(id);
      
      if (!fundingCall) {
        throw new Error(`Funding call with ID ${id} not found`);
      }
      
      // Generate embeddings for relevant fields
      const { embedding } = await embeddingService.generateFieldEmbeddings({
        schemeTitle: fundingCall.schemeTitle,
        description: fundingCall.description,
        researchAreas: fundingCall.researchAreas,
        applicantTypes: fundingCall.applicantTypes,
        grantTypes: fundingCall.grantTypes
      });
      
      if (embedding.length === 0) {
        console.warn(`Could not generate embedding for funding call ${id}`);
        return;
      }
      
      // Update the embedding directly in the database using raw SQL
      await prisma.$executeRaw`
        UPDATE funding_calls
        SET embedding = ${Prisma.raw(`'[${embedding.join(',')}]'::vector`)}
        WHERE id = ${id}
      `;
    } catch (error) {
      console.error(`Error updating embedding for funding call ${id}:`, error);
      throw error;
    }
  }
  
  /**
   * Perform a vector-based search for funding calls similar to the query
   */
  private async searchByVector(searchQuery: string, filters: SearchFilters = {}): Promise<SearchResult> {
    try {
      // Generate embedding for the search query
      const { embedding, error } = await embeddingService.generateEmbedding(searchQuery);
      
      if (error || embedding.length === 0) {
        return { 
          results: [],
          error: error || 'Could not generate embedding for search query' 
        };
      }
      
      // Build the SQL query with filters
      let whereConditions = buildPublicationWhereClause(filters);
      const limit = filters.limit || 5;
      // Get more results for ranking (3x the limit)
      const queryLimit = limit * 3;
      
      // Filter by applicant types if provided
      if (filters.applicantTypes && filters.applicantTypes.length > 0) {
        whereConditions += ` AND institution_types && ARRAY[${filters.applicantTypes.map(t => `'${t}'`).join(',')}]`;
      }
      
      // Filter by grant types if provided
      if (filters.grantTypes && filters.grantTypes.length > 0) {
        whereConditions += ` AND funding_kinds && ARRAY[${filters.grantTypes.map(t => `'${t}'`).join(',')}]`;
      }
      
      // Filter by countries if provided
      if (filters.countries && filters.countries.length > 0) {
        whereConditions += ` AND (
          host_countries && ARRAY[${filters.countries.map(c => `'${c}'`).join(',')}] OR
          eligible_countries && ARRAY[${filters.countries.map(c => `'${c}'`).join(',')}] OR
          host_countries && ARRAY[${filters.countries.map(c => `'${c}'`).join(',')}]
        )`;
      }
      
      // Perform vector search using cosine similarity
      const rawResults = await prisma.$queryRaw`
        SELECT 
          id, 
          scheme_title as "schemeTitle",
          agency_name as "agencyName",
          description,
          host_countries as "countryAvailability",
          eligible_countries as "eligibleApplicantCountries",
          institution_types as "applicantTypes",
          funding_kinds as "grantTypes",
          close_date as deadline,
          CASE
            WHEN amount_min IS NULL AND amount_max IS NULL THEN NULL
            ELSE trim(concat(COALESCE(currency, ''), ' ', COALESCE(amount_min::text, ''), CASE WHEN amount_max IS NOT NULL THEN concat(' - ', amount_max::text) ELSE '' END))
          END as "fundingAmount",
          eligibility_text as eligibility,
          disciplines as "researchAreas",
          official_urls as urls,
          contact_info as "contactInfo",
          created_at as "createdAt",
          updated_at as "updatedAt",
          1 - (embedding <=> ${Prisma.raw(`'[${embedding.join(',')}]'::vector`)}) as similarity
        FROM funding_calls
        WHERE embedding IS NOT NULL ${Prisma.raw(whereConditions)}
        ORDER BY similarity DESC
        LIMIT ${queryLimit}
      `;
      
      // Process the raw results
      const typedResults = rawResults as (FundingCall & { similarity: number })[];
      
      // Extract data for ranking
      const fundingCalls = typedResults.map(({ similarity, ...rest }) => rest as FundingCall);
      const similarities = typedResults.map(r => r.similarity);
      
      // Apply advanced ranking algorithm
      const rankingOptions = {
        prioritizeDeadlines: true,
        favoredApplicantTypes: filters?.applicantTypes,
        favoredGrantTypes: filters?.grantTypes,
        favoredCountries: filters?.countries,
        // Extract research areas from the search query in the future
        userResearchAreas: this.extractResearchAreas(searchQuery)
      };
      
      const rankedResults = resultRankingService.rankResults(
        fundingCalls,
        similarities,
        rankingOptions
      );
      
      // Return only the requested number of results
      const limitedResults = rankedResults.slice(0, limit);
      
      return {
        results: limitedResults.map(r => r.fundingCall),
        similarity: limitedResults.map(r => r.score)
      };
    } catch (error) {
      console.error('Error performing vector search:', error);
      return {
        results: [],
        error: error instanceof Error ? error.message : String(error)
      };
    }
  }
  
  // Enhanced search methods are implemented below
  
  /**
   * Extract keywords from a search query
   * @param query The search query text
   * @returns An array of keywords
   */
  private extractKeywords(query: string): string[] {
    if (!query) return [];
    
    // Common words to exclude
    const stopWords = [
      'a', 'an', 'the', 'and', 'or', 'but', 'for', 'with', 
      'in', 'on', 'at', 'to', 'of', 'by', 'about',
      'is', 'are', 'am', 'was', 'were', 'be', 'been',
      'i', 'you', 'he', 'she', 'it', 'we', 'they',
      'this', 'that', 'these', 'those', 'me', 'him', 'her',
      'any', 'some', 'all', 'many', 'few', 'several',
      'can', 'could', 'will', 'would', 'shall', 'should',
      'may', 'might', 'must', 'have', 'has', 'had',
      'do', 'does', 'did', 'doing', 'done'
    ];
    
    // Domain-specific keywords to always include (even if they're part of other words)
    const domainKeywords = [
      'ai', 'ml', 'agriculture', 'agri', 'farm', 'food', 'crop',
      'bio', 'tech', 'health', 'med', 'edu', 'energy', 'climate',
      'quantum', 'nano', 'cyber', 'data', 'digital', 'robot',
      'sustain', 'green', 'renewable', 'social', 'economic',
      'science', 'research', 'innovation', 'development', 'engineering',
      'computer', 'software', 'hardware', 'network', 'security',
      'physics', 'chemistry', 'biology', 'medicine', 'healthcare',
      'environment', 'ecology', 'conservation', 'policy', 'governance',
      'art', 'humanities', 'history', 'culture', 'language',
      'education', 'learning', 'teaching', 'training', 'skills',
      'business', 'entrepreneurship', 'startup', 'industry', 'commercial',
      'finance', 'investment', 'funding', 'grant', 'scholarship'
    ];
    
    // Common funding-related phrases to detect
    const fundingPhrases = [
      'funding for', 'grants for', 'scholarships for',
      'funding in', 'grants in', 'scholarships in',
      'funding related to', 'grants related to', 'scholarships related to',
      'financial support for', 'financial aid for',
      'research funding', 'research grants', 'research scholarships',
      'development funding', 'development grants',
      'innovation funding', 'innovation grants',
      'project funding', 'project grants',
      'funding opportunities', 'grant opportunities'
    ];
    
    // Normalize the query
    const normalizedQuery = query.toLowerCase();
    
    // First check for funding phrases to extract research areas
    let extractedAreas: string[] = [];
    fundingPhrases.forEach(phrase => {
      const index = normalizedQuery.indexOf(phrase);
      if (index >= 0) {
        // Extract the text after the phrase
        const afterPhrase = normalizedQuery.substring(index + phrase.length).trim();
        // Extract up to the next punctuation or 5 words
        const endIndex = Math.min(
          afterPhrase.indexOf('.') >= 0 ? afterPhrase.indexOf('.') : Infinity,
          afterPhrase.indexOf('?') >= 0 ? afterPhrase.indexOf('?') : Infinity,
          afterPhrase.indexOf('!') >= 0 ? afterPhrase.indexOf('!') : Infinity,
          afterPhrase.split(/\s+/).slice(0, 5).join(' ').length
        );
        
        if (endIndex > 0) {
          const area = afterPhrase.substring(0, endIndex).trim();
          if (area.length > 2) {
            extractedAreas.push(area);
          }
        }
      }
    });
    
    // Check for domain-specific keywords
    const extractedDomainKeywords = [];
    for (const keyword of domainKeywords) {
      if (normalizedQuery.includes(keyword)) {
        extractedDomainKeywords.push(keyword);
      }
    }
    
    // Normalize and tokenize the query
    const tokens = query.toLowerCase()
      .replace(/[^\w\s]/g, ' ') // Replace non-word chars with spaces
      .split(/\s+/)             // Split on whitespace
      .filter(word => word.length > 2 && !stopWords.includes(word)); // Remove stop words and short words
    
    // Combine all extracted keywords
    const allKeywords = [...extractedAreas, ...extractedDomainKeywords, ...tokens];
    
    // Check for common patterns like "any X funding/grants"
    const patterns = [
      /(?:any|available|current|existing|new|recent)\s+(\w+(?:\s+\w+){0,2})\s+(?:funding|grants|opportunities|scholarships)/i,
      /(?:funding|grants|opportunities|scholarships)\s+(?:for|in|related to)\s+(\w+(?:\s+\w+){0,2})/i
    ];
    
    patterns.forEach(pattern => {
      const match = normalizedQuery.match(pattern);
      if (match && match[1]) {
        allKeywords.push(match[1].trim());
      }
    });
    
    // Add bigrams and trigrams for better matching
    for (let i = 0; i < tokens.length - 1; i++) {
      allKeywords.push(`${tokens[i]} ${tokens[i+1]}`);
      if (i < tokens.length - 2) {
        allKeywords.push(`${tokens[i]} ${tokens[i+1]} ${tokens[i+2]}`);
      }
    }
    
    // Log extracted keywords for debugging
    console.log('All extracted keywords:', allKeywords);
    
    // Remove duplicates and return
    return Array.from(new Set(allKeywords));
  }
  
  /**
   * Keyword-based search as a fallback or complementary approach
   */
  private async searchByKeywords(query: string, filters: SearchFilters = {}): Promise<SearchResult> {
    try {
      // Extract keywords from the search text
      const keywords = this.extractKeywords(query);
      
      if (keywords.length === 0) {
        return { results: [], error: 'No valid keywords found in search text' };
      }
      
      console.log('Extracted keywords:', keywords);
      
      // Build the SQL query with filters
      let whereConditions = buildPublicationWhereClause(filters);
      const limit = filters.limit || 5;
      // Get more results for ranking (3x the limit)
      const queryLimit = limit * 3;
      
      // Create search conditions for each keyword (using OR between keywords)
      const keywordConditions: string[] = [];
      
      // Process each keyword with different matching techniques
      keywords.forEach(keyword => {
        // Escape single quotes for SQL safety
        const safeKeyword = keyword.replace(/'/g, "''");
        
        // Add direct ILIKE matching
        keywordConditions.push(`
          scheme_title ILIKE '%${safeKeyword}%' OR 
          description ILIKE '%${safeKeyword}%' OR 
          agency_name ILIKE '%${safeKeyword}%' OR
          EXISTS (
            SELECT 1 FROM unnest(disciplines) area
            WHERE area ILIKE '%${safeKeyword}%'
          )
        `);
        
        // Add word boundary matching for more precise matches
        keywordConditions.push(`
          scheme_title ~* '\\y${safeKeyword}\\y' OR 
          description ~* '\\y${safeKeyword}\\y' OR 
          agency_name ~* '\\y${safeKeyword}\\y' OR
          EXISTS (
            SELECT 1 FROM unnest(disciplines) area
            WHERE area ~* '\\y${safeKeyword}\\y'
          )
        `);
        
        // Add trigram similarity for fuzzy matching (if keyword is long enough)
        if (safeKeyword.length > 3) {
          keywordConditions.push(`
            similarity(scheme_title, '${safeKeyword}') > 0.3 OR
            similarity(description, '${safeKeyword}') > 0.3 OR
            similarity(agency_name, '${safeKeyword}') > 0.3 OR
            EXISTS (
              SELECT 1 FROM unnest(disciplines) area
              WHERE similarity(area, '${safeKeyword}') > 0.3
            )
          `);
        }
        
        // Add ts_vector matching for full-text search capabilities
        const tsQuery = safeKeyword.split(/\s+/).join(' & ');
        keywordConditions.push(`
          to_tsvector('english', scheme_title) @@ to_tsquery('english', '${tsQuery}') OR
          to_tsvector('english', description) @@ to_tsquery('english', '${tsQuery}') OR
          to_tsvector('english', array_to_string(disciplines, ' ')) @@ to_tsquery('english', '${tsQuery}') OR
          to_tsvector('english', agency_name) @@ to_tsquery('english', '${tsQuery}')
        `);
      });
      
      // Combine all keyword conditions with OR
      whereConditions += ` AND (${keywordConditions.join(' OR ')})`;
      
      // Add applicant type filter
      if (filters.applicantTypes && filters.applicantTypes.length > 0) {
        whereConditions += ` AND institution_types && ARRAY[${filters.applicantTypes.map(t => `'${t}'`).join(',')}]`;
      }
      
      // Add grant type filter
      if (filters.grantTypes && filters.grantTypes.length > 0) {
        whereConditions += ` AND funding_kinds && ARRAY[${filters.grantTypes.map(t => `'${t}'`).join(',')}]`;
      }
      
      // Add country filter
      if (filters.countries && filters.countries.length > 0) {
        whereConditions += ` AND (
          host_countries && ARRAY[${filters.countries.map(c => `'${c}'`).join(',')}] OR
          eligible_countries && ARRAY[${filters.countries.map(c => `'${c}'`).join(',')}] OR
          host_countries && ARRAY[${filters.countries.map(c => `'${c}'`).join(',')}] OR
          'global' = ANY(host_countries) OR
          'worldwide' = ANY(host_countries) OR
          'any' = ANY(host_countries) OR
          'international' = ANY(host_countries) OR
          'all' = ANY(host_countries)
        )`;
      }
      
      // Create a more sophisticated ranking expression
      const rankExpressions: string[] = [];
      
      keywords.forEach(keyword => {
        // Escape single quotes for SQL safety
        const safeKeyword = keyword.replace(/'/g, "''");
        
        rankExpressions.push(`
          (CASE WHEN scheme_title ILIKE '%${safeKeyword}%' THEN 2.0 ELSE 0 END) +
          (CASE WHEN description ILIKE '%${safeKeyword}%' THEN 1.0 ELSE 0 END) +
          (CASE WHEN EXISTS (
            SELECT 1 FROM unnest(disciplines) area
            WHERE area ILIKE '%${safeKeyword}%'
          ) THEN 1.5 ELSE 0 END) +
          (CASE WHEN agency_name ILIKE '%${safeKeyword}%' THEN 0.5 ELSE 0 END) +
          (CASE WHEN scheme_title ~* '\\y${safeKeyword}\\y' THEN 3.0 ELSE 0 END) +
          (CASE WHEN EXISTS (
            SELECT 1 FROM unnest(disciplines) area
            WHERE area ~* '\\y${safeKeyword}\\y'
          ) THEN 2.5 ELSE 0 END)
        `);
      });
      
      const rankExpression = rankExpressions.join(' + ');
      
      const sqlQuery = `
        SELECT 
          id, 
          scheme_title as "schemeTitle",
          agency_name as "agencyName",
          description,
          host_countries as "countryAvailability",
          eligible_countries as "eligibleApplicantCountries",
          institution_types as "applicantTypes",
          funding_kinds as "grantTypes",
          close_date as deadline,
          CASE
            WHEN amount_min IS NULL AND amount_max IS NULL THEN NULL
            ELSE trim(concat(COALESCE(currency, ''), ' ', COALESCE(amount_min::text, ''), CASE WHEN amount_max IS NOT NULL THEN concat(' - ', amount_max::text) ELSE '' END))
          END as "fundingAmount",
          eligibility_text as eligibility,
          disciplines as "researchAreas",
          official_urls as urls,
          contact_info as "contactInfo",
          created_at as "createdAt",
          updated_at as "updatedAt",
          ${rankExpression} as similarity
        FROM funding_calls
        WHERE 1=1 ${whereConditions}
        ORDER BY similarity DESC
        LIMIT ${queryLimit}
      `;
      
      console.log('Executing keyword search query');
      
      // Execute the query
      const results = await prisma.$queryRawUnsafe(sqlQuery) as (FundingCall & { similarity: number })[];
      
      console.log(`Found ${results.length} results from keyword search`);
      
      // Extract data for ranking
      const fundingCalls = results.map(({ similarity, ...rest }) => rest as FundingCall);
      const similarities = results.map(r => parseFloat(r.similarity as any));
      
      // Apply advanced ranking algorithm
      const rankingOptions = {
        prioritizeDeadlines: true,
        favoredApplicantTypes: filters.applicantTypes,
        favoredGrantTypes: filters.grantTypes,
        favoredCountries: filters.countries,
        userResearchAreas: keywords
      };
      
      const rankedResults = resultRankingService.rankResults(
        fundingCalls,
        similarities,
        rankingOptions
      );
      
      // Return only the requested number of results
      const limitedResults = rankedResults.slice(0, limit);
      
      return {
        results: limitedResults.map(r => r.fundingCall),
        similarity: limitedResults.map(r => r.score)
      };
    } catch (error) {
      console.error('Error during keyword search:', error);
      return {
        results: [],
        error: `Keyword search failed: ${error instanceof Error ? error.message : String(error)}`
      };
    }
  }
  
  /**
   * Combined search using both vector and keyword approaches
   */
  async searchFundingCalls(query: string, filters: SearchFilters = {}): Promise<SearchResult> {
    try {
      const searchResult = await recommendationSearchService.search({
        inputMode: 'research_area',
        query: { researchArea: query },
        filters: {
          eligibleCountries: filters.countries || [],
          institutionTypes: filters.applicantTypes || [],
          fundingKinds: filters.grantTypes || [],
          includeExpired: Boolean(filters.includeExpired),
          limit: filters.limit || 5,
        },
        access: filters.access,
      });

      return {
        results: searchResult.rawResults.map((item) => recommendationSearchService.toLegacyFundingCall(item)),
        similarity: searchResult.rawResults.map((item) => item.score)
      };
    } catch (error) {
      console.error('Error in combined search:', error);
      return {
        results: [],
        error: error instanceof Error ? error.message : String(error)
      };
    }
  }
  
  /**
   * Extract research areas from a search query
   * @param query The search query text
   * @returns An array of potential research areas
   */
  private extractResearchAreas(query: string): string[] {
    if (!query) return [];
    
    // Common research-related terms that might indicate a field of study
    const researchTerms = [
      'research', 'study', 'project', 'investigation', 
      'development', 'analysis', 'science', 'engineering',
      'technology', 'medicine', 'health', 'biology',
      'chemistry', 'physics', 'computer', 'software',
      'data', 'artificial intelligence', 'machine learning',
      'cloud', 'quantum', 'nano', 'renewable', 'climate',
      'sustainability', 'education', 'social', 'economic',
      'arts', 'humanities', 'agriculture', 'farming',
      'food', 'crops', 'agricultural', 'agri', 'agritech',
      'biotechnology', 'bioscience', 'environmental'
    ];
    
    // Direct research area mapping for common queries
    const directMappings: Record<string, string[]> = {
      'ai': ['Artificial Intelligence', 'Machine Learning'],
      'artificial intelligence': ['Artificial Intelligence', 'Machine Learning'],
      'machine learning': ['Machine Learning', 'Artificial Intelligence'],
      'agriculture': ['Agriculture', 'Sustainable Agriculture', 'Food Technology'],
      'farming': ['Agriculture', 'Sustainable Agriculture'],
      'food': ['Food Technology', 'Agriculture', 'Nutrition Science'],
      'health': ['Public Health', 'Medicine', 'Healthcare'],
      'medical': ['Medicine', 'Healthcare', 'Public Health'],
      'education': ['Education', 'Social Development'],
      'climate': ['Climate Change', 'Environmental Science', 'Sustainability'],
      'environment': ['Environmental Science', 'Sustainability'],
      'energy': ['Sustainable Energy', 'Renewable Energy'],
      'renewable': ['Renewable Energy', 'Sustainable Energy'],
      'social': ['Social Development', 'Social Science'],
      'computer science': ['Computer Science', 'Software Engineering'],
      'software': ['Software Engineering', 'Computer Science'],
      'data science': ['Data Science', 'Computer Science', 'Artificial Intelligence']
    };
    
    // Normalize the query
    const normalizedQuery = query.toLowerCase();
    
    // Check for direct mappings first
    const areas: string[] = [];
    
    // Add direct mappings if found
    Object.entries(directMappings).forEach(([key, mappedAreas]) => {
      if (normalizedQuery.includes(key)) {
        areas.push(...mappedAreas);
      }
    });
    
    // Extract potential research areas based on common terms
    researchTerms.forEach(term => {
      const termIndex = normalizedQuery.indexOf(term);
      if (termIndex >= 0) {
        // Get context around the term (5 words before and after)
        const words = normalizedQuery.split(/\s+/);
        const wordIndex = normalizedQuery.substring(0, termIndex).split(/\s+/).length - 1;
        
        const start = Math.max(0, wordIndex - 2);
        const end = Math.min(words.length, wordIndex + 5);
        
        const potentialArea = words.slice(start, end).join(' ')
          .replace(/[,.;:!?()[\]]/g, '') // Remove punctuation
          .trim();
        
        if (potentialArea && potentialArea.length > term.length) {
          areas.push(potentialArea);
        } else {
          areas.push(term);
        }
      }
    });
    
    // Also add any specific discipline mentions
    const disciplineIndicators = [
      'in the field of', 'related to', 'focusing on',
      'specializing in', 'with emphasis on', 'centered around',
      'about', 'in', 'for', 'regarding'
    ];
    
    disciplineIndicators.forEach(indicator => {
      const idx = normalizedQuery.indexOf(indicator);
      if (idx >= 0) {
        const afterIndicator = normalizedQuery.substring(idx + indicator.length).trim();
        const endOfPhrase = Math.min(
          afterIndicator.indexOf('.') >= 0 ? afterIndicator.indexOf('.') : Infinity,
          afterIndicator.indexOf(',') >= 0 ? afterIndicator.indexOf(',') : Infinity,
          afterIndicator.indexOf(' and ') >= 0 ? afterIndicator.indexOf(' and ') : Infinity,
          afterIndicator.length > 30 ? 30 : Infinity
        );
        
        if (endOfPhrase > 3) {
          areas.push(afterIndicator.substring(0, endOfPhrase).trim());
        }
      }
    });
    
    // Check for common query patterns like "any funding in X area?"
    const areaPatterns = [
      /any (?:funding|grants|opportunities) (?:in|for|related to) ([\w\s]+)(?:\?|$|\.)/i,
      /(?:funding|grants|opportunities) (?:in|for|related to) ([\w\s]+)(?:\?|$|\.)/i,
      /(?:looking for|need|want|searching for) (?:funding|grants) (?:in|for|related to) ([\w\s]+)(?:\?|$|\.)/i
    ];
    
    areaPatterns.forEach(pattern => {
      const match = normalizedQuery.match(pattern);
      if (match && match[1]) {
        const extractedArea = match[1].trim();
        if (extractedArea.length > 2) {
          areas.push(extractedArea);
          
          // Also add any direct mappings for this area
          Object.entries(directMappings).forEach(([key, mappedAreas]) => {
            if (extractedArea.includes(key)) {
              areas.push(...mappedAreas);
            }
          });
        }
      }
    });
    
    // Log the extracted areas for debugging
    console.log('Extracted research areas:', areas);
    
    // Remove duplicates and empty strings
    return Array.from(new Set(areas)).filter(Boolean);
  }
}

// Export a singleton instance
export const fundingCallsService = new FundingCallsService(); 
